<?php
/**
 * TrunkApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Vobiz
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vobiz API
 *
 * Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Vobiz\Test\Api;

use \Vobiz\Configuration;
use \Vobiz\ApiException;
use \Vobiz\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TrunkApiTest Class Doc Comment
 *
 * @category Class
 * @package  Vobiz
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TrunkApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV1AccountAccountIdCredentialsCredentialIdDelete
     *
     * Delete a Credential.
     *
     */
    public function testApiV1AccountAccountIdCredentialsCredentialIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdCredentialsCredentialIdPut
     *
     * Update a Credential.
     *
     */
    public function testApiV1AccountAccountIdCredentialsCredentialIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdCredentialsPost
     *
     * Create Credential.
     *
     */
    public function testApiV1AccountAccountIdCredentialsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdIpAclIpAclIdDelete
     *
     * Delete an IP ACL.
     *
     */
    public function testApiV1AccountAccountIdIpAclIpAclIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdIpAclIpAclIdPut
     *
     * Update an IP ACL.
     *
     */
    public function testApiV1AccountAccountIdIpAclIpAclIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdIpAclPost
     *
     * Create IP ACL.
     *
     */
    public function testApiV1AccountAccountIdIpAclPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdNumbersAssignDelete
     *
     * Unassign Number from Trunk.
     *
     */
    public function testApiV1AccountAccountIdNumbersAssignDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdNumbersAssignPost
     *
     * Assign Number to Trunk.
     *
     */
    public function testApiV1AccountAccountIdNumbersAssignPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdOriginationUrisPost
     *
     * Create Origination URI.
     *
     */
    public function testApiV1AccountAccountIdOriginationUrisPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdOriginationUrisUriIdDelete
     *
     * Delete an Origination URI.
     *
     */
    public function testApiV1AccountAccountIdOriginationUrisUriIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdOriginationUrisUriIdPut
     *
     * Update an Origination URI.
     *
     */
    public function testApiV1AccountAccountIdOriginationUrisUriIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdTrunksCredentialsGet
     *
     * List All Credentials.
     *
     */
    public function testApiV1AccountAccountIdTrunksCredentialsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdTrunksGet
     *
     * List All Trunks.
     *
     */
    public function testApiV1AccountAccountIdTrunksGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdTrunksIpAclGet
     *
     * List All IP ACLs.
     *
     */
    public function testApiV1AccountAccountIdTrunksIpAclGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdTrunksOriginationUrisGet
     *
     * List All Origination URIs.
     *
     */
    public function testApiV1AccountAccountIdTrunksOriginationUrisGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdTrunksPost
     *
     * Create Trunk.
     *
     */
    public function testApiV1AccountAccountIdTrunksPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdTrunksTrunkIdDelete
     *
     * Delete a Trunk.
     *
     */
    public function testApiV1AccountAccountIdTrunksTrunkIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdTrunksTrunkIdGet
     *
     * Retrieve a Trunk.
     *
     */
    public function testApiV1AccountAccountIdTrunksTrunkIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1AccountAccountIdTrunksTrunkIdPut
     *
     * Update a Trunk.
     *
     */
    public function testApiV1AccountAccountIdTrunksTrunkIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
