"""
    Vobiz API

    Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import Any, Dict, Optional
from typing_extensions import Annotated

from vobiz.api_client import ApiClient, RequestSerialized
from vobiz.api_response import ApiResponse
from vobiz.rest import RESTResponseType


class RecordingApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def api_v1_account_account_id_recording_get(
        self,
        account_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Records per request (default: 20, max: 100)")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="Pagination offset (default: 0)")] = None,
        call_uuid: Annotated[Optional[StrictStr], Field(description="Filter by specific call UUID")] = None,
        recording_type: Annotated[Optional[StrictStr], Field(description="Filter by type: trunk or extension")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """List All Recordings

        Retrieve a paginated list of call recordings for your account.

        :param account_id: (required)
        :type account_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param limit: Records per request (default: 20, max: 100)
        :type limit: int
        :param offset: Pagination offset (default: 0)
        :type offset: int
        :param call_uuid: Filter by specific call UUID
        :type call_uuid: str
        :param recording_type: Filter by type: trunk or extension
        :type recording_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_account_id_recording_get_serialize(
            account_id=account_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            limit=limit,
            offset=offset,
            call_uuid=call_uuid,
            recording_type=recording_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def api_v1_account_account_id_recording_get_with_http_info(
        self,
        account_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Records per request (default: 20, max: 100)")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="Pagination offset (default: 0)")] = None,
        call_uuid: Annotated[Optional[StrictStr], Field(description="Filter by specific call UUID")] = None,
        recording_type: Annotated[Optional[StrictStr], Field(description="Filter by type: trunk or extension")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """List All Recordings

        Retrieve a paginated list of call recordings for your account.

        :param account_id: (required)
        :type account_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param limit: Records per request (default: 20, max: 100)
        :type limit: int
        :param offset: Pagination offset (default: 0)
        :type offset: int
        :param call_uuid: Filter by specific call UUID
        :type call_uuid: str
        :param recording_type: Filter by type: trunk or extension
        :type recording_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_account_id_recording_get_serialize(
            account_id=account_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            limit=limit,
            offset=offset,
            call_uuid=call_uuid,
            recording_type=recording_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def api_v1_account_account_id_recording_get_without_preload_content(
        self,
        account_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        limit: Annotated[Optional[StrictInt], Field(description="Records per request (default: 20, max: 100)")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="Pagination offset (default: 0)")] = None,
        call_uuid: Annotated[Optional[StrictStr], Field(description="Filter by specific call UUID")] = None,
        recording_type: Annotated[Optional[StrictStr], Field(description="Filter by type: trunk or extension")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List All Recordings

        Retrieve a paginated list of call recordings for your account.

        :param account_id: (required)
        :type account_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param limit: Records per request (default: 20, max: 100)
        :type limit: int
        :param offset: Pagination offset (default: 0)
        :type offset: int
        :param call_uuid: Filter by specific call UUID
        :type call_uuid: str
        :param recording_type: Filter by type: trunk or extension
        :type recording_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_account_id_recording_get_serialize(
            account_id=account_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            limit=limit,
            offset=offset,
            call_uuid=call_uuid,
            recording_type=recording_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _api_v1_account_account_id_recording_get_serialize(
        self,
        account_id,
        x_auth_id,
        x_auth_token,
        content_type,
        limit,
        offset,
        call_uuid,
        recording_type,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if account_id is not None:
            _path_params['account_id'] = account_id
        # process the query parameters
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if call_uuid is not None:
            
            _query_params.append(('call_uuid', call_uuid))
            
        if recording_type is not None:
            
            _query_params.append(('recording_type', recording_type))
            
        # process the header parameters
        if x_auth_id is not None:
            _header_params['X-Auth-ID'] = x_auth_id
        if x_auth_token is not None:
            _header_params['X-Auth-Token'] = x_auth_token
        if content_type is not None:
            _header_params['Content-Type'] = content_type
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuthID', 
            'ApiKeyAuthToken'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/Account/{account_id}/Recording/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def api_v1_account_auth_id_export_recording_post(
        self,
        auth_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        body: Optional[Dict[str, Any]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Export Historical Recordings

        Export recordings as a downloadable archive sent via email (async). Returns 202 Accepted.

        :param auth_id: (required)
        :type auth_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param body:
        :type body: object
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_auth_id_export_recording_post_serialize(
            auth_id=auth_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            body=body,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def api_v1_account_auth_id_export_recording_post_with_http_info(
        self,
        auth_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        body: Optional[Dict[str, Any]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Export Historical Recordings

        Export recordings as a downloadable archive sent via email (async). Returns 202 Accepted.

        :param auth_id: (required)
        :type auth_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param body:
        :type body: object
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_auth_id_export_recording_post_serialize(
            auth_id=auth_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            body=body,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def api_v1_account_auth_id_export_recording_post_without_preload_content(
        self,
        auth_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        body: Optional[Dict[str, Any]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Export Historical Recordings

        Export recordings as a downloadable archive sent via email (async). Returns 202 Accepted.

        :param auth_id: (required)
        :type auth_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param body:
        :type body: object
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_auth_id_export_recording_post_serialize(
            auth_id=auth_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            body=body,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _api_v1_account_auth_id_export_recording_post_serialize(
        self,
        auth_id,
        x_auth_id,
        x_auth_token,
        content_type,
        body,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if auth_id is not None:
            _path_params['auth_id'] = auth_id
        # process the query parameters
        # process the header parameters
        if x_auth_id is not None:
            _header_params['X-Auth-ID'] = x_auth_id
        if x_auth_token is not None:
            _header_params['X-Auth-Token'] = x_auth_token
        if content_type is not None:
            _header_params['Content-Type'] = content_type
        # process the form parameters
        # process the body parameter
        if body is not None:
            _body_params = body


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuthID', 
            'ApiKeyAuthToken'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v1/Account/{auth_id}/export/recording/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def api_v1_account_auth_id_recording_bulk_delete_delete(
        self,
        auth_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        add_time__gte: Annotated[Optional[StrictStr], Field(description="Delete recordings on/after this date (YYYY-MM-DD HH:MM:SS)")] = None,
        add_time__lte: Annotated[Optional[StrictStr], Field(description="Delete recordings on/before this date")] = None,
        call_uuid: Annotated[Optional[StrictStr], Field(description="Delete recordings for specific call UUID")] = None,
        from_number: Annotated[Optional[StrictStr], Field(description="Delete by caller number (partial match)")] = None,
        to_number: Annotated[Optional[StrictStr], Field(description="Delete by destination number (partial match)")] = None,
        recording_format: Annotated[Optional[StrictStr], Field(description="mp3 or wav")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Bulk Delete Recordings

        Delete multiple recordings matching filter criteria (async operation). Returns 202 Accepted.

        :param auth_id: (required)
        :type auth_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param add_time__gte: Delete recordings on/after this date (YYYY-MM-DD HH:MM:SS)
        :type add_time__gte: str
        :param add_time__lte: Delete recordings on/before this date
        :type add_time__lte: str
        :param call_uuid: Delete recordings for specific call UUID
        :type call_uuid: str
        :param from_number: Delete by caller number (partial match)
        :type from_number: str
        :param to_number: Delete by destination number (partial match)
        :type to_number: str
        :param recording_format: mp3 or wav
        :type recording_format: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_auth_id_recording_bulk_delete_delete_serialize(
            auth_id=auth_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            add_time__gte=add_time__gte,
            add_time__lte=add_time__lte,
            call_uuid=call_uuid,
            from_number=from_number,
            to_number=to_number,
            recording_format=recording_format,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def api_v1_account_auth_id_recording_bulk_delete_delete_with_http_info(
        self,
        auth_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        add_time__gte: Annotated[Optional[StrictStr], Field(description="Delete recordings on/after this date (YYYY-MM-DD HH:MM:SS)")] = None,
        add_time__lte: Annotated[Optional[StrictStr], Field(description="Delete recordings on/before this date")] = None,
        call_uuid: Annotated[Optional[StrictStr], Field(description="Delete recordings for specific call UUID")] = None,
        from_number: Annotated[Optional[StrictStr], Field(description="Delete by caller number (partial match)")] = None,
        to_number: Annotated[Optional[StrictStr], Field(description="Delete by destination number (partial match)")] = None,
        recording_format: Annotated[Optional[StrictStr], Field(description="mp3 or wav")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Bulk Delete Recordings

        Delete multiple recordings matching filter criteria (async operation). Returns 202 Accepted.

        :param auth_id: (required)
        :type auth_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param add_time__gte: Delete recordings on/after this date (YYYY-MM-DD HH:MM:SS)
        :type add_time__gte: str
        :param add_time__lte: Delete recordings on/before this date
        :type add_time__lte: str
        :param call_uuid: Delete recordings for specific call UUID
        :type call_uuid: str
        :param from_number: Delete by caller number (partial match)
        :type from_number: str
        :param to_number: Delete by destination number (partial match)
        :type to_number: str
        :param recording_format: mp3 or wav
        :type recording_format: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_auth_id_recording_bulk_delete_delete_serialize(
            auth_id=auth_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            add_time__gte=add_time__gte,
            add_time__lte=add_time__lte,
            call_uuid=call_uuid,
            from_number=from_number,
            to_number=to_number,
            recording_format=recording_format,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def api_v1_account_auth_id_recording_bulk_delete_delete_without_preload_content(
        self,
        auth_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        add_time__gte: Annotated[Optional[StrictStr], Field(description="Delete recordings on/after this date (YYYY-MM-DD HH:MM:SS)")] = None,
        add_time__lte: Annotated[Optional[StrictStr], Field(description="Delete recordings on/before this date")] = None,
        call_uuid: Annotated[Optional[StrictStr], Field(description="Delete recordings for specific call UUID")] = None,
        from_number: Annotated[Optional[StrictStr], Field(description="Delete by caller number (partial match)")] = None,
        to_number: Annotated[Optional[StrictStr], Field(description="Delete by destination number (partial match)")] = None,
        recording_format: Annotated[Optional[StrictStr], Field(description="mp3 or wav")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Bulk Delete Recordings

        Delete multiple recordings matching filter criteria (async operation). Returns 202 Accepted.

        :param auth_id: (required)
        :type auth_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param add_time__gte: Delete recordings on/after this date (YYYY-MM-DD HH:MM:SS)
        :type add_time__gte: str
        :param add_time__lte: Delete recordings on/before this date
        :type add_time__lte: str
        :param call_uuid: Delete recordings for specific call UUID
        :type call_uuid: str
        :param from_number: Delete by caller number (partial match)
        :type from_number: str
        :param to_number: Delete by destination number (partial match)
        :type to_number: str
        :param recording_format: mp3 or wav
        :type recording_format: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_auth_id_recording_bulk_delete_delete_serialize(
            auth_id=auth_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            add_time__gte=add_time__gte,
            add_time__lte=add_time__lte,
            call_uuid=call_uuid,
            from_number=from_number,
            to_number=to_number,
            recording_format=recording_format,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _api_v1_account_auth_id_recording_bulk_delete_delete_serialize(
        self,
        auth_id,
        x_auth_id,
        x_auth_token,
        content_type,
        add_time__gte,
        add_time__lte,
        call_uuid,
        from_number,
        to_number,
        recording_format,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if auth_id is not None:
            _path_params['auth_id'] = auth_id
        # process the query parameters
        if add_time__gte is not None:
            
            _query_params.append(('add_time__gte', add_time__gte))
            
        if add_time__lte is not None:
            
            _query_params.append(('add_time__lte', add_time__lte))
            
        if call_uuid is not None:
            
            _query_params.append(('call_uuid', call_uuid))
            
        if from_number is not None:
            
            _query_params.append(('from_number', from_number))
            
        if to_number is not None:
            
            _query_params.append(('to_number', to_number))
            
        if recording_format is not None:
            
            _query_params.append(('recording_format', recording_format))
            
        # process the header parameters
        if x_auth_id is not None:
            _header_params['X-Auth-ID'] = x_auth_id
        if x_auth_token is not None:
            _header_params['X-Auth-Token'] = x_auth_token
        if content_type is not None:
            _header_params['Content-Type'] = content_type
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuthID', 
            'ApiKeyAuthToken'
        ]

        return self.api_client.param_serialize(
            method='DELETE',
            resource_path='/api/v1/Account/{auth_id}/Recording/BulkDelete/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def api_v1_account_auth_id_recording_delete(
        self,
        auth_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Delete a Recording

        Permanently delete a specific recording. Returns 204 No Content.

        :param auth_id: (required)
        :type auth_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_auth_id_recording_delete_serialize(
            auth_id=auth_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def api_v1_account_auth_id_recording_delete_with_http_info(
        self,
        auth_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Delete a Recording

        Permanently delete a specific recording. Returns 204 No Content.

        :param auth_id: (required)
        :type auth_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_auth_id_recording_delete_serialize(
            auth_id=auth_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def api_v1_account_auth_id_recording_delete_without_preload_content(
        self,
        auth_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Delete a Recording

        Permanently delete a specific recording. Returns 204 No Content.

        :param auth_id: (required)
        :type auth_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_auth_id_recording_delete_serialize(
            auth_id=auth_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _api_v1_account_auth_id_recording_delete_serialize(
        self,
        auth_id,
        x_auth_id,
        x_auth_token,
        content_type,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if auth_id is not None:
            _path_params['auth_id'] = auth_id
        # process the query parameters
        # process the header parameters
        if x_auth_id is not None:
            _header_params['X-Auth-ID'] = x_auth_id
        if x_auth_token is not None:
            _header_params['X-Auth-Token'] = x_auth_token
        if content_type is not None:
            _header_params['Content-Type'] = content_type
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuthID', 
            'ApiKeyAuthToken'
        ]

        return self.api_client.param_serialize(
            method='DELETE',
            resource_path='/api/v1/Account/{auth_id}/Recording/{}/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def api_v1_account_auth_id_recording_get(
        self,
        auth_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Retrieve a Recording

        Get detailed information about a specific recording.

        :param auth_id: (required)
        :type auth_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_auth_id_recording_get_serialize(
            auth_id=auth_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def api_v1_account_auth_id_recording_get_with_http_info(
        self,
        auth_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Retrieve a Recording

        Get detailed information about a specific recording.

        :param auth_id: (required)
        :type auth_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_auth_id_recording_get_serialize(
            auth_id=auth_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def api_v1_account_auth_id_recording_get_without_preload_content(
        self,
        auth_id: StrictStr,
        x_auth_id: Optional[StrictStr] = None,
        x_auth_token: Optional[StrictStr] = None,
        content_type: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Retrieve a Recording

        Get detailed information about a specific recording.

        :param auth_id: (required)
        :type auth_id: str
        :param x_auth_id:
        :type x_auth_id: str
        :param x_auth_token:
        :type x_auth_token: str
        :param content_type:
        :type content_type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._api_v1_account_auth_id_recording_get_serialize(
            auth_id=auth_id,
            x_auth_id=x_auth_id,
            x_auth_token=x_auth_token,
            content_type=content_type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _api_v1_account_auth_id_recording_get_serialize(
        self,
        auth_id,
        x_auth_id,
        x_auth_token,
        content_type,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if auth_id is not None:
            _path_params['auth_id'] = auth_id
        # process the query parameters
        # process the header parameters
        if x_auth_id is not None:
            _header_params['X-Auth-ID'] = x_auth_id
        if x_auth_token is not None:
            _header_params['X-Auth-Token'] = x_auth_token
        if content_type is not None:
            _header_params['Content-Type'] = content_type
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuthID', 
            'ApiKeyAuthToken'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/Account/{auth_id}/Recording/{}/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


