// <auto-generated>
/*
 * Vobiz API
 *
 * Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Vobiz.Client;
using System.Diagnostics.CodeAnalysis;

namespace Vobiz.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IAccountApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        AccountApiEvents Events { get; }

        /// <summary>
        /// Get Balance
        /// </summary>
        /// <remarks>
        /// Retrieve the balance for a specific account and currency. Replace &#39;INR&#39; with your currency code.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AccountAccountIdBalanceINRGetApiResponse"/>&gt;</returns>
        Task<IApiV1AccountAccountIdBalanceINRGetApiResponse> ApiV1AccountAccountIdBalanceINRGetAsync(string accountId, Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Balance
        /// </summary>
        /// <remarks>
        /// Retrieve the balance for a specific account and currency. Replace &#39;INR&#39; with your currency code.
        /// </remarks>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AccountAccountIdBalanceINRGetApiResponse"/>?&gt;</returns>
        Task<IApiV1AccountAccountIdBalanceINRGetApiResponse?> ApiV1AccountAccountIdBalanceINRGetOrDefaultAsync(string accountId, Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Transactions
        /// </summary>
        /// <remarks>
        /// Retrieve a list of transactions for a specific account.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="limit">Records per page (default: 50) (optional)</param>
        /// <param name="offset">Pagination offset (default: 0) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AccountAccountIdTransactionsGetApiResponse"/>&gt;</returns>
        Task<IApiV1AccountAccountIdTransactionsGetApiResponse> ApiV1AccountAccountIdTransactionsGetAsync(string accountId, Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, Option<int> limit = default, Option<int> offset = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Transactions
        /// </summary>
        /// <remarks>
        /// Retrieve a list of transactions for a specific account.
        /// </remarks>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="limit">Records per page (default: 50) (optional)</param>
        /// <param name="offset">Pagination offset (default: 0) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AccountAccountIdTransactionsGetApiResponse"/>?&gt;</returns>
        Task<IApiV1AccountAccountIdTransactionsGetApiResponse?> ApiV1AccountAccountIdTransactionsGetOrDefaultAsync(string accountId, Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, Option<int> limit = default, Option<int> offset = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Concurrency
        /// </summary>
        /// <remarks>
        /// Retrieve current concurrent call count and capacity.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authId"></param>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AccountAuthIdConcurrencyGetApiResponse"/>&gt;</returns>
        Task<IApiV1AccountAuthIdConcurrencyGetApiResponse> ApiV1AccountAuthIdConcurrencyGetAsync(string authId, Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Concurrency
        /// </summary>
        /// <remarks>
        /// Retrieve current concurrent call count and capacity.
        /// </remarks>
        /// <param name="authId"></param>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AccountAuthIdConcurrencyGetApiResponse"/>?&gt;</returns>
        Task<IApiV1AccountAuthIdConcurrencyGetApiResponse?> ApiV1AccountAuthIdConcurrencyGetOrDefaultAsync(string authId, Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieve Account Details
        /// </summary>
        /// <remarks>
        /// Retrieve complete account details including pricing tier, credentials, and account settings.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AuthMeGetApiResponse"/>&gt;</returns>
        Task<IApiV1AuthMeGetApiResponse> ApiV1AuthMeGetAsync(Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieve Account Details
        /// </summary>
        /// <remarks>
        /// Retrieve complete account details including pricing tier, credentials, and account settings.
        /// </remarks>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AuthMeGetApiResponse"/>?&gt;</returns>
        Task<IApiV1AuthMeGetApiResponse?> ApiV1AuthMeGetOrDefaultAsync(Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IApiV1AccountAccountIdBalanceINRGetApiResponse"/>
    /// </summary>
    public interface IApiV1AccountAccountIdBalanceINRGetApiResponse : Vobiz.Client.IApiResponse
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="IApiV1AccountAccountIdTransactionsGetApiResponse"/>
    /// </summary>
    public interface IApiV1AccountAccountIdTransactionsGetApiResponse : Vobiz.Client.IApiResponse
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="IApiV1AccountAuthIdConcurrencyGetApiResponse"/>
    /// </summary>
    public interface IApiV1AccountAuthIdConcurrencyGetApiResponse : Vobiz.Client.IApiResponse
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="IApiV1AuthMeGetApiResponse"/>
    /// </summary>
    public interface IApiV1AuthMeGetApiResponse : Vobiz.Client.IApiResponse
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class AccountApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnApiV1AccountAccountIdBalanceINRGet;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorApiV1AccountAccountIdBalanceINRGet;

        internal void ExecuteOnApiV1AccountAccountIdBalanceINRGet(AccountApi.ApiV1AccountAccountIdBalanceINRGetApiResponse apiResponse)
        {
            OnApiV1AccountAccountIdBalanceINRGet?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorApiV1AccountAccountIdBalanceINRGet(Exception exception)
        {
            OnErrorApiV1AccountAccountIdBalanceINRGet?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnApiV1AccountAccountIdTransactionsGet;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorApiV1AccountAccountIdTransactionsGet;

        internal void ExecuteOnApiV1AccountAccountIdTransactionsGet(AccountApi.ApiV1AccountAccountIdTransactionsGetApiResponse apiResponse)
        {
            OnApiV1AccountAccountIdTransactionsGet?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorApiV1AccountAccountIdTransactionsGet(Exception exception)
        {
            OnErrorApiV1AccountAccountIdTransactionsGet?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnApiV1AccountAuthIdConcurrencyGet;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorApiV1AccountAuthIdConcurrencyGet;

        internal void ExecuteOnApiV1AccountAuthIdConcurrencyGet(AccountApi.ApiV1AccountAuthIdConcurrencyGetApiResponse apiResponse)
        {
            OnApiV1AccountAuthIdConcurrencyGet?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorApiV1AccountAuthIdConcurrencyGet(Exception exception)
        {
            OnErrorApiV1AccountAuthIdConcurrencyGet?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnApiV1AuthMeGet;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorApiV1AuthMeGet;

        internal void ExecuteOnApiV1AuthMeGet(AccountApi.ApiV1AuthMeGetApiResponse apiResponse)
        {
            OnApiV1AuthMeGet?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorApiV1AuthMeGet(Exception exception)
        {
            OnErrorApiV1AuthMeGet?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class AccountApi : IAccountApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<AccountApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public AccountApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="ApiKeyProvider"/>
        /// </summary>
        public TokenProvider<ApiKeyToken> ApiKeyProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AccountApi(ILogger<AccountApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, AccountApiEvents accountApiEvents,
            TokenProvider<ApiKeyToken> apiKeyProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<AccountApi>();
            HttpClient = httpClient;
            Events = accountApiEvents;
            ApiKeyProvider = apiKeyProvider;
        }

        partial void FormatApiV1AccountAccountIdBalanceINRGet(ref string accountId, ref Option<string> xAuthID, ref Option<string> xAuthToken, ref Option<string> contentType);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        /// <returns></returns>
        private void ValidateApiV1AccountAccountIdBalanceINRGet(string accountId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType)
        {
            if (accountId == null)
                throw new ArgumentNullException(nameof(accountId));

            if (xAuthID.IsSet && xAuthID.Value == null)
                throw new ArgumentNullException(nameof(xAuthID));

            if (xAuthToken.IsSet && xAuthToken.Value == null)
                throw new ArgumentNullException(nameof(xAuthToken));

            if (contentType.IsSet && contentType.Value == null)
                throw new ArgumentNullException(nameof(contentType));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        private void AfterApiV1AccountAccountIdBalanceINRGetDefaultImplementation(IApiV1AccountAccountIdBalanceINRGetApiResponse apiResponseLocalVar, string accountId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType)
        {
            bool suppressDefaultLog = false;
            AfterApiV1AccountAccountIdBalanceINRGet(ref suppressDefaultLog, apiResponseLocalVar, accountId, xAuthID, xAuthToken, contentType);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        partial void AfterApiV1AccountAccountIdBalanceINRGet(ref bool suppressDefaultLog, IApiV1AccountAccountIdBalanceINRGetApiResponse apiResponseLocalVar, string accountId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        private void OnErrorApiV1AccountAccountIdBalanceINRGetDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string accountId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorApiV1AccountAccountIdBalanceINRGet(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, accountId, xAuthID, xAuthToken, contentType);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        partial void OnErrorApiV1AccountAccountIdBalanceINRGet(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string accountId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType);

        /// <summary>
        /// Get Balance Retrieve the balance for a specific account and currency. Replace &#39;INR&#39; with your currency code.
        /// </summary>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AccountAccountIdBalanceINRGetApiResponse"/>&gt;</returns>
        public async Task<IApiV1AccountAccountIdBalanceINRGetApiResponse?> ApiV1AccountAccountIdBalanceINRGetOrDefaultAsync(string accountId, Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ApiV1AccountAccountIdBalanceINRGetAsync(accountId, xAuthID, xAuthToken, contentType, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Get Balance Retrieve the balance for a specific account and currency. Replace &#39;INR&#39; with your currency code.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AccountAccountIdBalanceINRGetApiResponse"/>&gt;</returns>
        public async Task<IApiV1AccountAccountIdBalanceINRGetApiResponse> ApiV1AccountAccountIdBalanceINRGetAsync(string accountId, Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateApiV1AccountAccountIdBalanceINRGet(accountId, xAuthID, xAuthToken, contentType);

                FormatApiV1AccountAccountIdBalanceINRGet(ref accountId, ref xAuthID, ref xAuthToken, ref contentType);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v1/account/{account_id}/balance/INR"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/api/v1/account/{account_id}/balance/INR");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Baccount_id%7D", Uri.EscapeDataString(accountId.ToString()));

                    if (xAuthID.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("X-Auth-ID", ClientUtils.ParameterToString(xAuthID.Value));

                    if (xAuthToken.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("X-Auth-Token", ClientUtils.ParameterToString(xAuthToken.Value));

                    if (contentType.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("Content-Type", ClientUtils.ParameterToString(contentType.Value));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Auth-ID", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    ApiKeyToken apiKeyTokenLocalVar2 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Auth-Token", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar2);
                    apiKeyTokenLocalVar2.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<ApiV1AccountAccountIdBalanceINRGetApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<ApiV1AccountAccountIdBalanceINRGetApiResponse>();
                        ApiV1AccountAccountIdBalanceINRGetApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v1/account/{account_id}/balance/INR", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterApiV1AccountAccountIdBalanceINRGetDefaultImplementation(apiResponseLocalVar, accountId, xAuthID, xAuthToken, contentType);

                        Events.ExecuteOnApiV1AccountAccountIdBalanceINRGet(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorApiV1AccountAccountIdBalanceINRGetDefaultImplementation(e, "/api/v1/account/{account_id}/balance/INR", uriBuilderLocalVar.Path, accountId, xAuthID, xAuthToken, contentType);
                Events.ExecuteOnErrorApiV1AccountAccountIdBalanceINRGet(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ApiV1AccountAccountIdBalanceINRGetApiResponse"/>
        /// </summary>
        public partial class ApiV1AccountAccountIdBalanceINRGetApiResponse : Vobiz.Client.ApiResponse, IApiV1AccountAccountIdBalanceINRGetApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<ApiV1AccountAccountIdBalanceINRGetApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="ApiV1AccountAccountIdBalanceINRGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ApiV1AccountAccountIdBalanceINRGetApiResponse(ILogger<ApiV1AccountAccountIdBalanceINRGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="ApiV1AccountAccountIdBalanceINRGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ApiV1AccountAccountIdBalanceINRGetApiResponse(ILogger<ApiV1AccountAccountIdBalanceINRGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatApiV1AccountAccountIdTransactionsGet(ref string accountId, ref Option<string> xAuthID, ref Option<string> xAuthToken, ref Option<string> contentType, ref Option<int> limit, ref Option<int> offset);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        /// <returns></returns>
        private void ValidateApiV1AccountAccountIdTransactionsGet(string accountId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType)
        {
            if (accountId == null)
                throw new ArgumentNullException(nameof(accountId));

            if (xAuthID.IsSet && xAuthID.Value == null)
                throw new ArgumentNullException(nameof(xAuthID));

            if (xAuthToken.IsSet && xAuthToken.Value == null)
                throw new ArgumentNullException(nameof(xAuthToken));

            if (contentType.IsSet && contentType.Value == null)
                throw new ArgumentNullException(nameof(contentType));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        /// <param name="limit"></param>
        /// <param name="offset"></param>
        private void AfterApiV1AccountAccountIdTransactionsGetDefaultImplementation(IApiV1AccountAccountIdTransactionsGetApiResponse apiResponseLocalVar, string accountId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType, Option<int> limit, Option<int> offset)
        {
            bool suppressDefaultLog = false;
            AfterApiV1AccountAccountIdTransactionsGet(ref suppressDefaultLog, apiResponseLocalVar, accountId, xAuthID, xAuthToken, contentType, limit, offset);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        /// <param name="limit"></param>
        /// <param name="offset"></param>
        partial void AfterApiV1AccountAccountIdTransactionsGet(ref bool suppressDefaultLog, IApiV1AccountAccountIdTransactionsGetApiResponse apiResponseLocalVar, string accountId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType, Option<int> limit, Option<int> offset);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        /// <param name="limit"></param>
        /// <param name="offset"></param>
        private void OnErrorApiV1AccountAccountIdTransactionsGetDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string accountId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType, Option<int> limit, Option<int> offset)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorApiV1AccountAccountIdTransactionsGet(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, accountId, xAuthID, xAuthToken, contentType, limit, offset);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        /// <param name="limit"></param>
        /// <param name="offset"></param>
        partial void OnErrorApiV1AccountAccountIdTransactionsGet(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string accountId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType, Option<int> limit, Option<int> offset);

        /// <summary>
        /// Get Transactions Retrieve a list of transactions for a specific account.
        /// </summary>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="limit">Records per page (default: 50) (optional)</param>
        /// <param name="offset">Pagination offset (default: 0) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AccountAccountIdTransactionsGetApiResponse"/>&gt;</returns>
        public async Task<IApiV1AccountAccountIdTransactionsGetApiResponse?> ApiV1AccountAccountIdTransactionsGetOrDefaultAsync(string accountId, Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, Option<int> limit = default, Option<int> offset = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ApiV1AccountAccountIdTransactionsGetAsync(accountId, xAuthID, xAuthToken, contentType, limit, offset, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Get Transactions Retrieve a list of transactions for a specific account.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId"></param>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="limit">Records per page (default: 50) (optional)</param>
        /// <param name="offset">Pagination offset (default: 0) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AccountAccountIdTransactionsGetApiResponse"/>&gt;</returns>
        public async Task<IApiV1AccountAccountIdTransactionsGetApiResponse> ApiV1AccountAccountIdTransactionsGetAsync(string accountId, Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, Option<int> limit = default, Option<int> offset = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateApiV1AccountAccountIdTransactionsGet(accountId, xAuthID, xAuthToken, contentType);

                FormatApiV1AccountAccountIdTransactionsGet(ref accountId, ref xAuthID, ref xAuthToken, ref contentType, ref limit, ref offset);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v1/account/{account_id}/transactions"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/api/v1/account/{account_id}/transactions");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Baccount_id%7D", Uri.EscapeDataString(accountId.ToString()));

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (limit.IsSet)
                        parseQueryStringLocalVar["limit"] = ClientUtils.ParameterToString(limit.Value);

                    if (offset.IsSet)
                        parseQueryStringLocalVar["offset"] = ClientUtils.ParameterToString(offset.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    if (xAuthID.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("X-Auth-ID", ClientUtils.ParameterToString(xAuthID.Value));

                    if (xAuthToken.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("X-Auth-Token", ClientUtils.ParameterToString(xAuthToken.Value));

                    if (contentType.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("Content-Type", ClientUtils.ParameterToString(contentType.Value));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Auth-ID", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    ApiKeyToken apiKeyTokenLocalVar2 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Auth-Token", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar2);
                    apiKeyTokenLocalVar2.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<ApiV1AccountAccountIdTransactionsGetApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<ApiV1AccountAccountIdTransactionsGetApiResponse>();
                        ApiV1AccountAccountIdTransactionsGetApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v1/account/{account_id}/transactions", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterApiV1AccountAccountIdTransactionsGetDefaultImplementation(apiResponseLocalVar, accountId, xAuthID, xAuthToken, contentType, limit, offset);

                        Events.ExecuteOnApiV1AccountAccountIdTransactionsGet(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorApiV1AccountAccountIdTransactionsGetDefaultImplementation(e, "/api/v1/account/{account_id}/transactions", uriBuilderLocalVar.Path, accountId, xAuthID, xAuthToken, contentType, limit, offset);
                Events.ExecuteOnErrorApiV1AccountAccountIdTransactionsGet(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ApiV1AccountAccountIdTransactionsGetApiResponse"/>
        /// </summary>
        public partial class ApiV1AccountAccountIdTransactionsGetApiResponse : Vobiz.Client.ApiResponse, IApiV1AccountAccountIdTransactionsGetApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<ApiV1AccountAccountIdTransactionsGetApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="ApiV1AccountAccountIdTransactionsGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ApiV1AccountAccountIdTransactionsGetApiResponse(ILogger<ApiV1AccountAccountIdTransactionsGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="ApiV1AccountAccountIdTransactionsGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ApiV1AccountAccountIdTransactionsGetApiResponse(ILogger<ApiV1AccountAccountIdTransactionsGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatApiV1AccountAuthIdConcurrencyGet(ref string authId, ref Option<string> xAuthID, ref Option<string> xAuthToken, ref Option<string> contentType);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="authId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        /// <returns></returns>
        private void ValidateApiV1AccountAuthIdConcurrencyGet(string authId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType)
        {
            if (authId == null)
                throw new ArgumentNullException(nameof(authId));

            if (xAuthID.IsSet && xAuthID.Value == null)
                throw new ArgumentNullException(nameof(xAuthID));

            if (xAuthToken.IsSet && xAuthToken.Value == null)
                throw new ArgumentNullException(nameof(xAuthToken));

            if (contentType.IsSet && contentType.Value == null)
                throw new ArgumentNullException(nameof(contentType));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="authId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        private void AfterApiV1AccountAuthIdConcurrencyGetDefaultImplementation(IApiV1AccountAuthIdConcurrencyGetApiResponse apiResponseLocalVar, string authId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType)
        {
            bool suppressDefaultLog = false;
            AfterApiV1AccountAuthIdConcurrencyGet(ref suppressDefaultLog, apiResponseLocalVar, authId, xAuthID, xAuthToken, contentType);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="authId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        partial void AfterApiV1AccountAuthIdConcurrencyGet(ref bool suppressDefaultLog, IApiV1AccountAuthIdConcurrencyGetApiResponse apiResponseLocalVar, string authId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="authId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        private void OnErrorApiV1AccountAuthIdConcurrencyGetDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string authId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorApiV1AccountAuthIdConcurrencyGet(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, authId, xAuthID, xAuthToken, contentType);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="authId"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        partial void OnErrorApiV1AccountAuthIdConcurrencyGet(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string authId, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType);

        /// <summary>
        /// Get Concurrency Retrieve current concurrent call count and capacity.
        /// </summary>
        /// <param name="authId"></param>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AccountAuthIdConcurrencyGetApiResponse"/>&gt;</returns>
        public async Task<IApiV1AccountAuthIdConcurrencyGetApiResponse?> ApiV1AccountAuthIdConcurrencyGetOrDefaultAsync(string authId, Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ApiV1AccountAuthIdConcurrencyGetAsync(authId, xAuthID, xAuthToken, contentType, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Get Concurrency Retrieve current concurrent call count and capacity.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authId"></param>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AccountAuthIdConcurrencyGetApiResponse"/>&gt;</returns>
        public async Task<IApiV1AccountAuthIdConcurrencyGetApiResponse> ApiV1AccountAuthIdConcurrencyGetAsync(string authId, Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateApiV1AccountAuthIdConcurrencyGet(authId, xAuthID, xAuthToken, contentType);

                FormatApiV1AccountAuthIdConcurrencyGet(ref authId, ref xAuthID, ref xAuthToken, ref contentType);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v1/account/{auth_id}/concurrency"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/api/v1/account/{auth_id}/concurrency");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bauth_id%7D", Uri.EscapeDataString(authId.ToString()));

                    if (xAuthID.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("X-Auth-ID", ClientUtils.ParameterToString(xAuthID.Value));

                    if (xAuthToken.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("X-Auth-Token", ClientUtils.ParameterToString(xAuthToken.Value));

                    if (contentType.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("Content-Type", ClientUtils.ParameterToString(contentType.Value));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Auth-ID", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    ApiKeyToken apiKeyTokenLocalVar2 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Auth-Token", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar2);
                    apiKeyTokenLocalVar2.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<ApiV1AccountAuthIdConcurrencyGetApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<ApiV1AccountAuthIdConcurrencyGetApiResponse>();
                        ApiV1AccountAuthIdConcurrencyGetApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v1/account/{auth_id}/concurrency", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterApiV1AccountAuthIdConcurrencyGetDefaultImplementation(apiResponseLocalVar, authId, xAuthID, xAuthToken, contentType);

                        Events.ExecuteOnApiV1AccountAuthIdConcurrencyGet(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorApiV1AccountAuthIdConcurrencyGetDefaultImplementation(e, "/api/v1/account/{auth_id}/concurrency", uriBuilderLocalVar.Path, authId, xAuthID, xAuthToken, contentType);
                Events.ExecuteOnErrorApiV1AccountAuthIdConcurrencyGet(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ApiV1AccountAuthIdConcurrencyGetApiResponse"/>
        /// </summary>
        public partial class ApiV1AccountAuthIdConcurrencyGetApiResponse : Vobiz.Client.ApiResponse, IApiV1AccountAuthIdConcurrencyGetApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<ApiV1AccountAuthIdConcurrencyGetApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="ApiV1AccountAuthIdConcurrencyGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ApiV1AccountAuthIdConcurrencyGetApiResponse(ILogger<ApiV1AccountAuthIdConcurrencyGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="ApiV1AccountAuthIdConcurrencyGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ApiV1AccountAuthIdConcurrencyGetApiResponse(ILogger<ApiV1AccountAuthIdConcurrencyGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatApiV1AuthMeGet(ref Option<string> xAuthID, ref Option<string> xAuthToken, ref Option<string> contentType);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        /// <returns></returns>
        private void ValidateApiV1AuthMeGet(Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType)
        {
            if (xAuthID.IsSet && xAuthID.Value == null)
                throw new ArgumentNullException(nameof(xAuthID));

            if (xAuthToken.IsSet && xAuthToken.Value == null)
                throw new ArgumentNullException(nameof(xAuthToken));

            if (contentType.IsSet && contentType.Value == null)
                throw new ArgumentNullException(nameof(contentType));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        private void AfterApiV1AuthMeGetDefaultImplementation(IApiV1AuthMeGetApiResponse apiResponseLocalVar, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType)
        {
            bool suppressDefaultLog = false;
            AfterApiV1AuthMeGet(ref suppressDefaultLog, apiResponseLocalVar, xAuthID, xAuthToken, contentType);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        partial void AfterApiV1AuthMeGet(ref bool suppressDefaultLog, IApiV1AuthMeGetApiResponse apiResponseLocalVar, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        private void OnErrorApiV1AuthMeGetDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorApiV1AuthMeGet(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, xAuthID, xAuthToken, contentType);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="xAuthID"></param>
        /// <param name="xAuthToken"></param>
        /// <param name="contentType"></param>
        partial void OnErrorApiV1AuthMeGet(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> xAuthID, Option<string> xAuthToken, Option<string> contentType);

        /// <summary>
        /// Retrieve Account Details Retrieve complete account details including pricing tier, credentials, and account settings.
        /// </summary>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AuthMeGetApiResponse"/>&gt;</returns>
        public async Task<IApiV1AuthMeGetApiResponse?> ApiV1AuthMeGetOrDefaultAsync(Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ApiV1AuthMeGetAsync(xAuthID, xAuthToken, contentType, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Retrieve Account Details Retrieve complete account details including pricing tier, credentials, and account settings.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAuthID"> (optional)</param>
        /// <param name="xAuthToken"> (optional)</param>
        /// <param name="contentType"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiV1AuthMeGetApiResponse"/>&gt;</returns>
        public async Task<IApiV1AuthMeGetApiResponse> ApiV1AuthMeGetAsync(Option<string> xAuthID = default, Option<string> xAuthToken = default, Option<string> contentType = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateApiV1AuthMeGet(xAuthID, xAuthToken, contentType);

                FormatApiV1AuthMeGet(ref xAuthID, ref xAuthToken, ref contentType);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v1/auth/me"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/api/v1/auth/me");

                    if (xAuthID.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("X-Auth-ID", ClientUtils.ParameterToString(xAuthID.Value));

                    if (xAuthToken.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("X-Auth-Token", ClientUtils.ParameterToString(xAuthToken.Value));

                    if (contentType.IsSet)
                        httpRequestMessageLocalVar.Headers.Add("Content-Type", ClientUtils.ParameterToString(contentType.Value));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Auth-ID", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    ApiKeyToken apiKeyTokenLocalVar2 = (ApiKeyToken) await ApiKeyProvider.GetAsync("X-Auth-Token", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar2);
                    apiKeyTokenLocalVar2.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<ApiV1AuthMeGetApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<ApiV1AuthMeGetApiResponse>();
                        ApiV1AuthMeGetApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v1/auth/me", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterApiV1AuthMeGetDefaultImplementation(apiResponseLocalVar, xAuthID, xAuthToken, contentType);

                        Events.ExecuteOnApiV1AuthMeGet(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorApiV1AuthMeGetDefaultImplementation(e, "/api/v1/auth/me", uriBuilderLocalVar.Path, xAuthID, xAuthToken, contentType);
                Events.ExecuteOnErrorApiV1AuthMeGet(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ApiV1AuthMeGetApiResponse"/>
        /// </summary>
        public partial class ApiV1AuthMeGetApiResponse : Vobiz.Client.ApiResponse, IApiV1AuthMeGetApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<ApiV1AuthMeGetApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="ApiV1AuthMeGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ApiV1AuthMeGetApiResponse(ILogger<ApiV1AuthMeGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="ApiV1AuthMeGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ApiV1AuthMeGetApiResponse(ILogger<ApiV1AuthMeGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
