<?php
/**
 * AccountApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Vobiz
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vobiz API
 *
 * Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vobiz\VobizApi;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Vobiz\ApiException;
use Vobiz\Configuration;
use Vobiz\FormDataProcessor;
use Vobiz\HeaderSelector;
use Vobiz\ObjectSerializer;

/**
 * AccountApi Class Doc Comment
 *
 * @category Class
 * @package  Vobiz
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccountApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiV1AccountAccountIdBalanceINRGet' => [
            'application/json',
        ],
        'apiV1AccountAccountIdTransactionsGet' => [
            'application/json',
        ],
        'apiV1AccountAuthIdConcurrencyGet' => [
            'application/json',
        ],
        'apiV1AuthMeGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV1AccountAccountIdBalanceINRGet
     *
     * Get Balance
     *
     * @param  string $account_id account_id (required)
     * @param  string|null $x_auth_id x_auth_id (optional)
     * @param  string|null $x_auth_token x_auth_token (optional)
     * @param  string|null $content_type content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAccountIdBalanceINRGet'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1AccountAccountIdBalanceINRGet($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountAccountIdBalanceINRGet'][0])
    {
        $this->apiV1AccountAccountIdBalanceINRGetWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $contentType);
    }

    /**
     * Operation apiV1AccountAccountIdBalanceINRGetWithHttpInfo
     *
     * Get Balance
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAccountIdBalanceINRGet'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1AccountAccountIdBalanceINRGetWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountAccountIdBalanceINRGet'][0])
    {
        $request = $this->apiV1AccountAccountIdBalanceINRGetRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1AccountAccountIdBalanceINRGetAsync
     *
     * Get Balance
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAccountIdBalanceINRGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountAccountIdBalanceINRGetAsync($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountAccountIdBalanceINRGet'][0])
    {
        return $this->apiV1AccountAccountIdBalanceINRGetAsyncWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1AccountAccountIdBalanceINRGetAsyncWithHttpInfo
     *
     * Get Balance
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAccountIdBalanceINRGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountAccountIdBalanceINRGetAsyncWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountAccountIdBalanceINRGet'][0])
    {
        $returnType = '';
        $request = $this->apiV1AccountAccountIdBalanceINRGetRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1AccountAccountIdBalanceINRGet'
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAccountIdBalanceINRGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1AccountAccountIdBalanceINRGetRequest($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountAccountIdBalanceINRGet'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling apiV1AccountAccountIdBalanceINRGet'
            );
        }





        $resourcePath = '/api/v1/account/{account_id}/balance/INR';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_auth_id !== null) {
            $headerParams['X-Auth-ID'] = ObjectSerializer::toHeaderValue($x_auth_id);
        }
        // header params
        if ($x_auth_token !== null) {
            $headerParams['X-Auth-Token'] = ObjectSerializer::toHeaderValue($x_auth_token);
        }
        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'account_id' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-ID');
        if ($apiKey !== null) {
            $headers['X-Auth-ID'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-Token');
        if ($apiKey !== null) {
            $headers['X-Auth-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1AccountAccountIdTransactionsGet
     *
     * Get Transactions
     *
     * @param  string $account_id account_id (required)
     * @param  string|null $x_auth_id x_auth_id (optional)
     * @param  string|null $x_auth_token x_auth_token (optional)
     * @param  string|null $content_type content_type (optional)
     * @param  int|null $limit Records per page (default: 50) (optional)
     * @param  int|null $offset Pagination offset (default: 0) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAccountIdTransactionsGet'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1AccountAccountIdTransactionsGet($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $limit = null, $offset = null, string $contentType = self::contentTypes['apiV1AccountAccountIdTransactionsGet'][0])
    {
        $this->apiV1AccountAccountIdTransactionsGetWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $limit, $offset, $contentType);
    }

    /**
     * Operation apiV1AccountAccountIdTransactionsGetWithHttpInfo
     *
     * Get Transactions
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  int|null $limit Records per page (default: 50) (optional)
     * @param  int|null $offset Pagination offset (default: 0) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAccountIdTransactionsGet'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1AccountAccountIdTransactionsGetWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $limit = null, $offset = null, string $contentType = self::contentTypes['apiV1AccountAccountIdTransactionsGet'][0])
    {
        $request = $this->apiV1AccountAccountIdTransactionsGetRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $limit, $offset, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1AccountAccountIdTransactionsGetAsync
     *
     * Get Transactions
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  int|null $limit Records per page (default: 50) (optional)
     * @param  int|null $offset Pagination offset (default: 0) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAccountIdTransactionsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountAccountIdTransactionsGetAsync($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $limit = null, $offset = null, string $contentType = self::contentTypes['apiV1AccountAccountIdTransactionsGet'][0])
    {
        return $this->apiV1AccountAccountIdTransactionsGetAsyncWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $limit, $offset, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1AccountAccountIdTransactionsGetAsyncWithHttpInfo
     *
     * Get Transactions
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  int|null $limit Records per page (default: 50) (optional)
     * @param  int|null $offset Pagination offset (default: 0) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAccountIdTransactionsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountAccountIdTransactionsGetAsyncWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $limit = null, $offset = null, string $contentType = self::contentTypes['apiV1AccountAccountIdTransactionsGet'][0])
    {
        $returnType = '';
        $request = $this->apiV1AccountAccountIdTransactionsGetRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $limit, $offset, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1AccountAccountIdTransactionsGet'
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  int|null $limit Records per page (default: 50) (optional)
     * @param  int|null $offset Pagination offset (default: 0) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAccountIdTransactionsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1AccountAccountIdTransactionsGetRequest($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $limit = null, $offset = null, string $contentType = self::contentTypes['apiV1AccountAccountIdTransactionsGet'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling apiV1AccountAccountIdTransactionsGet'
            );
        }







        $resourcePath = '/api/v1/account/{account_id}/transactions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_auth_id !== null) {
            $headerParams['X-Auth-ID'] = ObjectSerializer::toHeaderValue($x_auth_id);
        }
        // header params
        if ($x_auth_token !== null) {
            $headerParams['X-Auth-Token'] = ObjectSerializer::toHeaderValue($x_auth_token);
        }
        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'account_id' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-ID');
        if ($apiKey !== null) {
            $headers['X-Auth-ID'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-Token');
        if ($apiKey !== null) {
            $headers['X-Auth-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1AccountAuthIdConcurrencyGet
     *
     * Get Concurrency
     *
     * @param  string $auth_id auth_id (required)
     * @param  string|null $x_auth_id x_auth_id (optional)
     * @param  string|null $x_auth_token x_auth_token (optional)
     * @param  string|null $content_type content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAuthIdConcurrencyGet'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1AccountAuthIdConcurrencyGet($auth_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountAuthIdConcurrencyGet'][0])
    {
        $this->apiV1AccountAuthIdConcurrencyGetWithHttpInfo($auth_id, $x_auth_id, $x_auth_token, $content_type, $contentType);
    }

    /**
     * Operation apiV1AccountAuthIdConcurrencyGetWithHttpInfo
     *
     * Get Concurrency
     *
     * @param  string $auth_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAuthIdConcurrencyGet'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1AccountAuthIdConcurrencyGetWithHttpInfo($auth_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountAuthIdConcurrencyGet'][0])
    {
        $request = $this->apiV1AccountAuthIdConcurrencyGetRequest($auth_id, $x_auth_id, $x_auth_token, $content_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1AccountAuthIdConcurrencyGetAsync
     *
     * Get Concurrency
     *
     * @param  string $auth_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAuthIdConcurrencyGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountAuthIdConcurrencyGetAsync($auth_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountAuthIdConcurrencyGet'][0])
    {
        return $this->apiV1AccountAuthIdConcurrencyGetAsyncWithHttpInfo($auth_id, $x_auth_id, $x_auth_token, $content_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1AccountAuthIdConcurrencyGetAsyncWithHttpInfo
     *
     * Get Concurrency
     *
     * @param  string $auth_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAuthIdConcurrencyGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountAuthIdConcurrencyGetAsyncWithHttpInfo($auth_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountAuthIdConcurrencyGet'][0])
    {
        $returnType = '';
        $request = $this->apiV1AccountAuthIdConcurrencyGetRequest($auth_id, $x_auth_id, $x_auth_token, $content_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1AccountAuthIdConcurrencyGet'
     *
     * @param  string $auth_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountAuthIdConcurrencyGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1AccountAuthIdConcurrencyGetRequest($auth_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountAuthIdConcurrencyGet'][0])
    {

        // verify the required parameter 'auth_id' is set
        if ($auth_id === null || (is_array($auth_id) && count($auth_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $auth_id when calling apiV1AccountAuthIdConcurrencyGet'
            );
        }





        $resourcePath = '/api/v1/account/{auth_id}/concurrency';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_auth_id !== null) {
            $headerParams['X-Auth-ID'] = ObjectSerializer::toHeaderValue($x_auth_id);
        }
        // header params
        if ($x_auth_token !== null) {
            $headerParams['X-Auth-Token'] = ObjectSerializer::toHeaderValue($x_auth_token);
        }
        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($auth_id !== null) {
            $resourcePath = str_replace(
                '{' . 'auth_id' . '}',
                ObjectSerializer::toPathValue($auth_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-ID');
        if ($apiKey !== null) {
            $headers['X-Auth-ID'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-Token');
        if ($apiKey !== null) {
            $headers['X-Auth-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1AuthMeGet
     *
     * Retrieve Account Details
     *
     * @param  string|null $x_auth_id x_auth_id (optional)
     * @param  string|null $x_auth_token x_auth_token (optional)
     * @param  string|null $content_type content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AuthMeGet'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1AuthMeGet($x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AuthMeGet'][0])
    {
        $this->apiV1AuthMeGetWithHttpInfo($x_auth_id, $x_auth_token, $content_type, $contentType);
    }

    /**
     * Operation apiV1AuthMeGetWithHttpInfo
     *
     * Retrieve Account Details
     *
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AuthMeGet'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1AuthMeGetWithHttpInfo($x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AuthMeGet'][0])
    {
        $request = $this->apiV1AuthMeGetRequest($x_auth_id, $x_auth_token, $content_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1AuthMeGetAsync
     *
     * Retrieve Account Details
     *
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AuthMeGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AuthMeGetAsync($x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AuthMeGet'][0])
    {
        return $this->apiV1AuthMeGetAsyncWithHttpInfo($x_auth_id, $x_auth_token, $content_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1AuthMeGetAsyncWithHttpInfo
     *
     * Retrieve Account Details
     *
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AuthMeGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AuthMeGetAsyncWithHttpInfo($x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AuthMeGet'][0])
    {
        $returnType = '';
        $request = $this->apiV1AuthMeGetRequest($x_auth_id, $x_auth_token, $content_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1AuthMeGet'
     *
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AuthMeGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1AuthMeGetRequest($x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AuthMeGet'][0])
    {





        $resourcePath = '/api/v1/auth/me';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_auth_id !== null) {
            $headerParams['X-Auth-ID'] = ObjectSerializer::toHeaderValue($x_auth_id);
        }
        // header params
        if ($x_auth_token !== null) {
            $headerParams['X-Auth-Token'] = ObjectSerializer::toHeaderValue($x_auth_token);
        }
        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-ID');
        if ($apiKey !== null) {
            $headers['X-Auth-ID'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-Token');
        if ($apiKey !== null) {
            $headers['X-Auth-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
