<?php
/**
 * SubAccountApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Vobiz
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Vobiz API
 *
 * Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Vobiz\VobizApi;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Vobiz\ApiException;
use Vobiz\Configuration;
use Vobiz\FormDataProcessor;
use Vobiz\HeaderSelector;
use Vobiz\ObjectSerializer;

/**
 * SubAccountApi Class Doc Comment
 *
 * @category Class
 * @package  Vobiz
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SubAccountApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiV1AccountsAccountIdSubAccountsGet' => [
            'application/json',
        ],
        'apiV1AccountsAccountIdSubAccountsPost' => [
            'application/json',
        ],
        'apiV1AccountsAccountIdSubAccountsSubAccountIdDelete' => [
            'application/json',
        ],
        'apiV1AccountsAccountIdSubAccountsSubAccountIdGet' => [
            'application/json',
        ],
        'apiV1AccountsAccountIdSubAccountsSubAccountIdPut' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsGet
     *
     * List All Sub-Accounts
     *
     * @param  string $account_id account_id (required)
     * @param  string|null $x_auth_id x_auth_id (optional)
     * @param  string|null $x_auth_token x_auth_token (optional)
     * @param  string|null $content_type content_type (optional)
     * @param  int|null $page Page number (optional)
     * @param  int|null $size Results per page (optional)
     * @param  bool|null $active_only Filter active sub-accounts only (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsGet'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1AccountsAccountIdSubAccountsGet($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $page = null, $size = null, $active_only = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsGet'][0])
    {
        $this->apiV1AccountsAccountIdSubAccountsGetWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $page, $size, $active_only, $contentType);
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsGetWithHttpInfo
     *
     * List All Sub-Accounts
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  int|null $page Page number (optional)
     * @param  int|null $size Results per page (optional)
     * @param  bool|null $active_only Filter active sub-accounts only (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsGet'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1AccountsAccountIdSubAccountsGetWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $page = null, $size = null, $active_only = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsGet'][0])
    {
        $request = $this->apiV1AccountsAccountIdSubAccountsGetRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $page, $size, $active_only, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsGetAsync
     *
     * List All Sub-Accounts
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  int|null $page Page number (optional)
     * @param  int|null $size Results per page (optional)
     * @param  bool|null $active_only Filter active sub-accounts only (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountsAccountIdSubAccountsGetAsync($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $page = null, $size = null, $active_only = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsGet'][0])
    {
        return $this->apiV1AccountsAccountIdSubAccountsGetAsyncWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $page, $size, $active_only, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsGetAsyncWithHttpInfo
     *
     * List All Sub-Accounts
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  int|null $page Page number (optional)
     * @param  int|null $size Results per page (optional)
     * @param  bool|null $active_only Filter active sub-accounts only (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountsAccountIdSubAccountsGetAsyncWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $page = null, $size = null, $active_only = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsGet'][0])
    {
        $returnType = '';
        $request = $this->apiV1AccountsAccountIdSubAccountsGetRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $page, $size, $active_only, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1AccountsAccountIdSubAccountsGet'
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  int|null $page Page number (optional)
     * @param  int|null $size Results per page (optional)
     * @param  bool|null $active_only Filter active sub-accounts only (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1AccountsAccountIdSubAccountsGetRequest($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $page = null, $size = null, $active_only = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsGet'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling apiV1AccountsAccountIdSubAccountsGet'
            );
        }








        $resourcePath = '/api/v1/accounts/{account_id}/sub-accounts/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $active_only,
            'active_only', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_auth_id !== null) {
            $headerParams['X-Auth-ID'] = ObjectSerializer::toHeaderValue($x_auth_id);
        }
        // header params
        if ($x_auth_token !== null) {
            $headerParams['X-Auth-Token'] = ObjectSerializer::toHeaderValue($x_auth_token);
        }
        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'account_id' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-ID');
        if ($apiKey !== null) {
            $headers['X-Auth-ID'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-Token');
        if ($apiKey !== null) {
            $headers['X-Auth-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsPost
     *
     * Create Sub-Account
     *
     * @param  string $account_id account_id (required)
     * @param  string|null $x_auth_id x_auth_id (optional)
     * @param  string|null $x_auth_token x_auth_token (optional)
     * @param  string|null $content_type content_type (optional)
     * @param  object|null $body body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsPost'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1AccountsAccountIdSubAccountsPost($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $body = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsPost'][0])
    {
        $this->apiV1AccountsAccountIdSubAccountsPostWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $body, $contentType);
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsPostWithHttpInfo
     *
     * Create Sub-Account
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsPost'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1AccountsAccountIdSubAccountsPostWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $body = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsPost'][0])
    {
        $request = $this->apiV1AccountsAccountIdSubAccountsPostRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsPostAsync
     *
     * Create Sub-Account
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountsAccountIdSubAccountsPostAsync($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $body = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsPost'][0])
    {
        return $this->apiV1AccountsAccountIdSubAccountsPostAsyncWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsPostAsyncWithHttpInfo
     *
     * Create Sub-Account
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountsAccountIdSubAccountsPostAsyncWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $body = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsPost'][0])
    {
        $returnType = '';
        $request = $this->apiV1AccountsAccountIdSubAccountsPostRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1AccountsAccountIdSubAccountsPost'
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1AccountsAccountIdSubAccountsPostRequest($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $body = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsPost'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling apiV1AccountsAccountIdSubAccountsPost'
            );
        }






        $resourcePath = '/api/v1/accounts/{account_id}/sub-accounts/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_auth_id !== null) {
            $headerParams['X-Auth-ID'] = ObjectSerializer::toHeaderValue($x_auth_id);
        }
        // header params
        if ($x_auth_token !== null) {
            $headerParams['X-Auth-Token'] = ObjectSerializer::toHeaderValue($x_auth_token);
        }
        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'account_id' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-ID');
        if ($apiKey !== null) {
            $headers['X-Auth-ID'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-Token');
        if ($apiKey !== null) {
            $headers['X-Auth-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsSubAccountIdDelete
     *
     * Delete a Sub-Account
     *
     * @param  string $account_id account_id (required)
     * @param  string|null $x_auth_id x_auth_id (optional)
     * @param  string|null $x_auth_token x_auth_token (optional)
     * @param  string|null $content_type content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdDelete'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdDelete($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdDelete'][0])
    {
        $this->apiV1AccountsAccountIdSubAccountsSubAccountIdDeleteWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $contentType);
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsSubAccountIdDeleteWithHttpInfo
     *
     * Delete a Sub-Account
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdDelete'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdDeleteWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdDelete'][0])
    {
        $request = $this->apiV1AccountsAccountIdSubAccountsSubAccountIdDeleteRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsSubAccountIdDeleteAsync
     *
     * Delete a Sub-Account
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdDeleteAsync($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdDelete'][0])
    {
        return $this->apiV1AccountsAccountIdSubAccountsSubAccountIdDeleteAsyncWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsSubAccountIdDeleteAsyncWithHttpInfo
     *
     * Delete a Sub-Account
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdDeleteAsyncWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdDelete'][0])
    {
        $returnType = '';
        $request = $this->apiV1AccountsAccountIdSubAccountsSubAccountIdDeleteRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1AccountsAccountIdSubAccountsSubAccountIdDelete'
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdDeleteRequest($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdDelete'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling apiV1AccountsAccountIdSubAccountsSubAccountIdDelete'
            );
        }





        $resourcePath = '/api/v1/accounts/{account_id}/sub-accounts/:sub_account_id';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_auth_id !== null) {
            $headerParams['X-Auth-ID'] = ObjectSerializer::toHeaderValue($x_auth_id);
        }
        // header params
        if ($x_auth_token !== null) {
            $headerParams['X-Auth-Token'] = ObjectSerializer::toHeaderValue($x_auth_token);
        }
        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'account_id' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-ID');
        if ($apiKey !== null) {
            $headers['X-Auth-ID'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-Token');
        if ($apiKey !== null) {
            $headers['X-Auth-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsSubAccountIdGet
     *
     * Retrieve a Sub-Account
     *
     * @param  string $account_id account_id (required)
     * @param  string|null $x_auth_id x_auth_id (optional)
     * @param  string|null $x_auth_token x_auth_token (optional)
     * @param  string|null $content_type content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdGet'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdGet($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdGet'][0])
    {
        $this->apiV1AccountsAccountIdSubAccountsSubAccountIdGetWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $contentType);
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsSubAccountIdGetWithHttpInfo
     *
     * Retrieve a Sub-Account
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdGet'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdGetWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdGet'][0])
    {
        $request = $this->apiV1AccountsAccountIdSubAccountsSubAccountIdGetRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsSubAccountIdGetAsync
     *
     * Retrieve a Sub-Account
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdGetAsync($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdGet'][0])
    {
        return $this->apiV1AccountsAccountIdSubAccountsSubAccountIdGetAsyncWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsSubAccountIdGetAsyncWithHttpInfo
     *
     * Retrieve a Sub-Account
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdGetAsyncWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdGet'][0])
    {
        $returnType = '';
        $request = $this->apiV1AccountsAccountIdSubAccountsSubAccountIdGetRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1AccountsAccountIdSubAccountsSubAccountIdGet'
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdGetRequest($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdGet'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling apiV1AccountsAccountIdSubAccountsSubAccountIdGet'
            );
        }





        $resourcePath = '/api/v1/accounts/{account_id}/sub-accounts/:sub_account_id';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_auth_id !== null) {
            $headerParams['X-Auth-ID'] = ObjectSerializer::toHeaderValue($x_auth_id);
        }
        // header params
        if ($x_auth_token !== null) {
            $headerParams['X-Auth-Token'] = ObjectSerializer::toHeaderValue($x_auth_token);
        }
        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'account_id' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-ID');
        if ($apiKey !== null) {
            $headers['X-Auth-ID'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-Token');
        if ($apiKey !== null) {
            $headers['X-Auth-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsSubAccountIdPut
     *
     * Update a Sub-Account
     *
     * @param  string $account_id account_id (required)
     * @param  string|null $x_auth_id x_auth_id (optional)
     * @param  string|null $x_auth_token x_auth_token (optional)
     * @param  string|null $content_type content_type (optional)
     * @param  object|null $body body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdPut'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdPut($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $body = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdPut'][0])
    {
        $this->apiV1AccountsAccountIdSubAccountsSubAccountIdPutWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $body, $contentType);
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsSubAccountIdPutWithHttpInfo
     *
     * Update a Sub-Account
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdPut'] to see the possible values for this operation
     *
     * @throws \Vobiz\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdPutWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $body = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdPut'][0])
    {
        $request = $this->apiV1AccountsAccountIdSubAccountsSubAccountIdPutRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsSubAccountIdPutAsync
     *
     * Update a Sub-Account
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdPutAsync($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $body = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdPut'][0])
    {
        return $this->apiV1AccountsAccountIdSubAccountsSubAccountIdPutAsyncWithHttpInfo($account_id, $x_auth_id, $x_auth_token, $content_type, $body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1AccountsAccountIdSubAccountsSubAccountIdPutAsyncWithHttpInfo
     *
     * Update a Sub-Account
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdPutAsyncWithHttpInfo($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $body = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdPut'][0])
    {
        $returnType = '';
        $request = $this->apiV1AccountsAccountIdSubAccountsSubAccountIdPutRequest($account_id, $x_auth_id, $x_auth_token, $content_type, $body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1AccountsAccountIdSubAccountsSubAccountIdPut'
     *
     * @param  string $account_id (required)
     * @param  string|null $x_auth_id (optional)
     * @param  string|null $x_auth_token (optional)
     * @param  string|null $content_type (optional)
     * @param  object|null $body (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1AccountsAccountIdSubAccountsSubAccountIdPutRequest($account_id, $x_auth_id = null, $x_auth_token = null, $content_type = null, $body = null, string $contentType = self::contentTypes['apiV1AccountsAccountIdSubAccountsSubAccountIdPut'][0])
    {

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling apiV1AccountsAccountIdSubAccountsSubAccountIdPut'
            );
        }






        $resourcePath = '/api/v1/accounts/{account_id}/sub-accounts/:sub_account_id';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_auth_id !== null) {
            $headerParams['X-Auth-ID'] = ObjectSerializer::toHeaderValue($x_auth_id);
        }
        // header params
        if ($x_auth_token !== null) {
            $headerParams['X-Auth-Token'] = ObjectSerializer::toHeaderValue($x_auth_token);
        }
        // header params
        if ($content_type !== null) {
            $headerParams['Content-Type'] = ObjectSerializer::toHeaderValue($content_type);
        }

        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{' . 'account_id' . '}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-ID');
        if ($apiKey !== null) {
            $headers['X-Auth-ID'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-Token');
        if ($apiKey !== null) {
            $headers['X-Auth-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
