/**
 * Vobiz API
 * Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://api.vobiz.ai';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum CallApiApiKeys {
    ApiKeyAuthID,
    ApiKeyAuthToken,
}

export class CallApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'ApiKeyAuthID': new ApiKeyAuth('header', 'X-Auth-ID'),
        'ApiKeyAuthToken': new ApiKeyAuth('header', 'X-Auth-Token'),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: CallApiApiKeys, value: string) {
        (this.authentications as any)[CallApiApiKeys[key]].apiKey = value;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * Send DTMF digits to an active call for automated IVR navigation.
     * @summary Send DTMF Digits
     * @param authId 
     * @param xAuthID 
     * @param xAuthToken 
     * @param contentType 
     * @param body 
     */
    public async apiV1AccountAuthIdCallDTMFPost (authId: string, xAuthID?: string, xAuthToken?: string, contentType?: string, body?: object, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/api/v1/Account/{auth_id}/Call/{}/DTMF/'
            .replace('{' + 'auth_id' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'authId' is not null or undefined
        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling apiV1AccountAuthIdCallDTMFPost.');
        }

        localVarHeaderParams['X-Auth-ID'] = ObjectSerializer.serialize(xAuthID, "string");
        localVarHeaderParams['X-Auth-Token'] = ObjectSerializer.serialize(xAuthToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(body, "object")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuthID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.ApiKeyAuthToken.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthToken.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Terminate an active call. Returns 204 No Content.
     * @summary Hang Up a Call
     * @param authId 
     * @param xAuthID 
     * @param xAuthToken 
     * @param contentType 
     */
    public async apiV1AccountAuthIdCallDelete (authId: string, xAuthID?: string, xAuthToken?: string, contentType?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/api/v1/Account/{auth_id}/Call/{}/'
            .replace('{' + 'auth_id' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'authId' is not null or undefined
        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling apiV1AccountAuthIdCallDelete.');
        }

        localVarHeaderParams['X-Auth-ID'] = ObjectSerializer.serialize(xAuthID, "string");
        localVarHeaderParams['X-Auth-Token'] = ObjectSerializer.serialize(xAuthToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'DELETE',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuthID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.ApiKeyAuthToken.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthToken.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Get a list of all call UUIDs for calls currently queued and waiting to connect. Max 20 results.
     * @summary Retrieve All Queued Calls
     * @param authId 
     * @param xAuthID 
     * @param xAuthToken 
     * @param contentType 
     * @param status Must be \&#39;queued\&#39;
     */
    public async apiV1AccountAuthIdCallGet (authId: string, xAuthID?: string, xAuthToken?: string, contentType?: string, status?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/api/v1/Account/{auth_id}/Call/'
            .replace('{' + 'auth_id' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'authId' is not null or undefined
        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling apiV1AccountAuthIdCallGet.');
        }

        if (status !== undefined) {
            localVarQueryParameters['status'] = ObjectSerializer.serialize(status, "string");
        }

        localVarHeaderParams['X-Auth-ID'] = ObjectSerializer.serialize(xAuthID, "string");
        localVarHeaderParams['X-Auth-Token'] = ObjectSerializer.serialize(xAuthToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuthID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.ApiKeyAuthToken.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthToken.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Get details of a specific queued call.
     * @summary Retrieve a Queued Call
     * @param authId 
     * @param xAuthID 
     * @param xAuthToken 
     * @param contentType 
     * @param status Must be \&#39;queued\&#39;
     */
    public async apiV1AccountAuthIdCallGet_1 (authId: string, xAuthID?: string, xAuthToken?: string, contentType?: string, status?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/api/v1/Account/{auth_id}/Call/{}/'
            .replace('{' + 'auth_id' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'authId' is not null or undefined
        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling apiV1AccountAuthIdCallGet_1.');
        }

        if (status !== undefined) {
            localVarQueryParameters['status'] = ObjectSerializer.serialize(status, "string");
        }

        localVarHeaderParams['X-Auth-ID'] = ObjectSerializer.serialize(xAuthID, "string");
        localVarHeaderParams['X-Auth-Token'] = ObjectSerializer.serialize(xAuthToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuthID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.ApiKeyAuthToken.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthToken.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Stop audio playback on an active call. Returns 204 No Content.
     * @summary Stop Playing Audio on a Call
     * @param authId 
     * @param xAuthID 
     * @param xAuthToken 
     * @param contentType 
     */
    public async apiV1AccountAuthIdCallPlayDelete (authId: string, xAuthID?: string, xAuthToken?: string, contentType?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/api/v1/Account/{auth_id}/Call/{}/Play/'
            .replace('{' + 'auth_id' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'authId' is not null or undefined
        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling apiV1AccountAuthIdCallPlayDelete.');
        }

        localVarHeaderParams['X-Auth-ID'] = ObjectSerializer.serialize(xAuthID, "string");
        localVarHeaderParams['X-Auth-Token'] = ObjectSerializer.serialize(xAuthToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'DELETE',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuthID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.ApiKeyAuthToken.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthToken.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Play audio file(s) during an active call.
     * @summary Play Audio on a Call
     * @param authId 
     * @param xAuthID 
     * @param xAuthToken 
     * @param contentType 
     * @param body 
     */
    public async apiV1AccountAuthIdCallPlayPost (authId: string, xAuthID?: string, xAuthToken?: string, contentType?: string, body?: object, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/api/v1/Account/{auth_id}/Call/{}/Play/'
            .replace('{' + 'auth_id' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'authId' is not null or undefined
        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling apiV1AccountAuthIdCallPlayPost.');
        }

        localVarHeaderParams['X-Auth-ID'] = ObjectSerializer.serialize(xAuthID, "string");
        localVarHeaderParams['X-Auth-Token'] = ObjectSerializer.serialize(xAuthToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(body, "object")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuthID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.ApiKeyAuthToken.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthToken.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Initiate an outbound call to a PSTN number or SIP endpoint. Supports bulk calls (up to 1000 destinations using < separator).
     * @summary Make an Outbound Call
     * @param authId 
     * @param xAuthID 
     * @param xAuthToken 
     * @param contentType 
     * @param body 
     */
    public async apiV1AccountAuthIdCallPost (authId: string, xAuthID?: string, xAuthToken?: string, contentType?: string, body?: object, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/api/v1/Account/{auth_id}/Call/'
            .replace('{' + 'auth_id' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'authId' is not null or undefined
        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling apiV1AccountAuthIdCallPost.');
        }

        localVarHeaderParams['X-Auth-ID'] = ObjectSerializer.serialize(xAuthID, "string");
        localVarHeaderParams['X-Auth-Token'] = ObjectSerializer.serialize(xAuthToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(body, "object")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuthID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.ApiKeyAuthToken.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthToken.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Transfer an in-progress call to a different URL for new call flow instructions.
     * @summary Transfer a Call
     * @param authId 
     * @param xAuthID 
     * @param xAuthToken 
     * @param contentType 
     * @param body 
     */
    public async apiV1AccountAuthIdCallPost_2 (authId: string, xAuthID?: string, xAuthToken?: string, contentType?: string, body?: object, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/api/v1/Account/{auth_id}/Call/{}/'
            .replace('{' + 'auth_id' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'authId' is not null or undefined
        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling apiV1AccountAuthIdCallPost_2.');
        }

        localVarHeaderParams['X-Auth-ID'] = ObjectSerializer.serialize(xAuthID, "string");
        localVarHeaderParams['X-Auth-Token'] = ObjectSerializer.serialize(xAuthToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(body, "object")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuthID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.ApiKeyAuthToken.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthToken.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Stop active recording(s) on a call. Returns 204 No Content.
     * @summary Stop Recording a Call
     * @param authId 
     * @param xAuthID 
     * @param xAuthToken 
     * @param contentType 
     */
    public async apiV1AccountAuthIdCallRecordDelete (authId: string, xAuthID?: string, xAuthToken?: string, contentType?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/api/v1/Account/{auth_id}/Call/{}/Record/'
            .replace('{' + 'auth_id' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'authId' is not null or undefined
        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling apiV1AccountAuthIdCallRecordDelete.');
        }

        localVarHeaderParams['X-Auth-ID'] = ObjectSerializer.serialize(xAuthID, "string");
        localVarHeaderParams['X-Auth-Token'] = ObjectSerializer.serialize(xAuthToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'DELETE',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuthID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.ApiKeyAuthToken.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthToken.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Begin recording an active call.
     * @summary Start Recording a Call
     * @param authId 
     * @param xAuthID 
     * @param xAuthToken 
     * @param contentType 
     * @param body 
     */
    public async apiV1AccountAuthIdCallRecordPost (authId: string, xAuthID?: string, xAuthToken?: string, contentType?: string, body?: object, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/api/v1/Account/{auth_id}/Call/{}/Record/'
            .replace('{' + 'auth_id' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'authId' is not null or undefined
        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling apiV1AccountAuthIdCallRecordPost.');
        }

        localVarHeaderParams['X-Auth-ID'] = ObjectSerializer.serialize(xAuthID, "string");
        localVarHeaderParams['X-Auth-Token'] = ObjectSerializer.serialize(xAuthToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(body, "object")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuthID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.ApiKeyAuthToken.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthToken.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Stop text-to-speech playback. Returns 204 No Content.
     * @summary Stop Speaking Text on a Call
     * @param authId 
     * @param xAuthID 
     * @param xAuthToken 
     * @param contentType 
     */
    public async apiV1AccountAuthIdCallSpeakDelete (authId: string, xAuthID?: string, xAuthToken?: string, contentType?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/api/v1/Account/{auth_id}/Call/{}/Speak/'
            .replace('{' + 'auth_id' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'authId' is not null or undefined
        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling apiV1AccountAuthIdCallSpeakDelete.');
        }

        localVarHeaderParams['X-Auth-ID'] = ObjectSerializer.serialize(xAuthID, "string");
        localVarHeaderParams['X-Auth-Token'] = ObjectSerializer.serialize(xAuthToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'DELETE',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuthID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.ApiKeyAuthToken.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthToken.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * Convert text to speech and play it during an active call. Supports 29 languages.
     * @summary Speak Text on a Call (TTS)
     * @param authId 
     * @param xAuthID 
     * @param xAuthToken 
     * @param contentType 
     * @param body 
     */
    public async apiV1AccountAuthIdCallSpeakPost (authId: string, xAuthID?: string, xAuthToken?: string, contentType?: string, body?: object, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/api/v1/Account/{auth_id}/Call/{}/Speak/'
            .replace('{' + 'auth_id' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'authId' is not null or undefined
        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling apiV1AccountAuthIdCallSpeakPost.');
        }

        localVarHeaderParams['X-Auth-ID'] = ObjectSerializer.serialize(xAuthID, "string");
        localVarHeaderParams['X-Auth-Token'] = ObjectSerializer.serialize(xAuthToken, "string");
        localVarHeaderParams['Content-Type'] = ObjectSerializer.serialize(contentType, "string");
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(body, "object")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuthID.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthID.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.ApiKeyAuthToken.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuthToken.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}
