/*
 * Vobiz API
 * Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.vobiz.api;

import ai.vobiz.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApplicationApi
 */
@Disabled
public class ApplicationApiTest {

    private final ApplicationApi api = new ApplicationApi();

    /**
     * Delete an Application
     *
     * Delete an application. Returns 204 No Content.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1AccountAuthIdApplicationDeleteTest() throws ApiException {
        String authId = null;
        String xAuthID = null;
        String xAuthToken = null;
        String contentType = null;
        api.apiV1AccountAuthIdApplicationDelete(authId, xAuthID, xAuthToken, contentType);
        // TODO: test validations
    }

    /**
     * List All Applications
     *
     * Retrieve all applications with pagination.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1AccountAuthIdApplicationGetTest() throws ApiException {
        String authId = null;
        String xAuthID = null;
        String xAuthToken = null;
        String contentType = null;
        Integer limit = null;
        Integer offset = null;
        api.apiV1AccountAuthIdApplicationGet(authId, xAuthID, xAuthToken, contentType, limit, offset);
        // TODO: test validations
    }

    /**
     * Retrieve an Application
     *
     * Get details of a specific application by its ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1AccountAuthIdApplicationGet_0Test() throws ApiException {
        String authId = null;
        String xAuthID = null;
        String xAuthToken = null;
        String contentType = null;
        api.apiV1AccountAuthIdApplicationGet_0(authId, xAuthID, xAuthToken, contentType);
        // TODO: test validations
    }

    /**
     * Create Application
     *
     * Create a new application with call handling URLs.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1AccountAuthIdApplicationPostTest() throws ApiException {
        String authId = null;
        String xAuthID = null;
        String xAuthToken = null;
        String contentType = null;
        Object body = null;
        api.apiV1AccountAuthIdApplicationPost(authId, xAuthID, xAuthToken, contentType, body);
        // TODO: test validations
    }

    /**
     * Update an Application
     *
     * Update an existing application&#39;s settings.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1AccountAuthIdApplicationPost_0Test() throws ApiException {
        String authId = null;
        String xAuthID = null;
        String xAuthToken = null;
        String contentType = null;
        Object body = null;
        api.apiV1AccountAuthIdApplicationPost_0(authId, xAuthID, xAuthToken, contentType, body);
        // TODO: test validations
    }

    /**
     * Unlink Number from Application
     *
     * Remove association between a phone number and application.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1AccountAuthIdNumbersApplicationDeleteTest() throws ApiException {
        String authId = null;
        String xAuthID = null;
        String xAuthToken = null;
        String contentType = null;
        api.apiV1AccountAuthIdNumbersApplicationDelete(authId, xAuthID, xAuthToken, contentType);
        // TODO: test validations
    }

    /**
     * Link Number to Application
     *
     * Associate a phone number with an application.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1AccountAuthIdNumbersApplicationPostTest() throws ApiException {
        String authId = null;
        String xAuthID = null;
        String xAuthToken = null;
        String contentType = null;
        Object body = null;
        api.apiV1AccountAuthIdNumbersApplicationPost(authId, xAuthID, xAuthToken, contentType, body);
        // TODO: test validations
    }

}
