/*
 * Vobiz API
 * Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.vobiz.api;

import ai.vobiz.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecordingApi
 */
@Disabled
public class RecordingApiTest {

    private final RecordingApi api = new RecordingApi();

    /**
     * List All Recordings
     *
     * Retrieve a paginated list of call recordings for your account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1AccountAccountIdRecordingGetTest() throws ApiException {
        String accountId = null;
        String xAuthID = null;
        String xAuthToken = null;
        String contentType = null;
        Integer limit = null;
        Integer offset = null;
        String callUuid = null;
        String recordingType = null;
        api.apiV1AccountAccountIdRecordingGet(accountId, xAuthID, xAuthToken, contentType, limit, offset, callUuid, recordingType);
        // TODO: test validations
    }

    /**
     * Export Historical Recordings
     *
     * Export recordings as a downloadable archive sent via email (async). Returns 202 Accepted.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1AccountAuthIdExportRecordingPostTest() throws ApiException {
        String authId = null;
        String xAuthID = null;
        String xAuthToken = null;
        String contentType = null;
        Object body = null;
        api.apiV1AccountAuthIdExportRecordingPost(authId, xAuthID, xAuthToken, contentType, body);
        // TODO: test validations
    }

    /**
     * Bulk Delete Recordings
     *
     * Delete multiple recordings matching filter criteria (async operation). Returns 202 Accepted.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1AccountAuthIdRecordingBulkDeleteDeleteTest() throws ApiException {
        String authId = null;
        String xAuthID = null;
        String xAuthToken = null;
        String contentType = null;
        String addTimeGte = null;
        String addTimeLte = null;
        String callUuid = null;
        String fromNumber = null;
        String toNumber = null;
        String recordingFormat = null;
        api.apiV1AccountAuthIdRecordingBulkDeleteDelete(authId, xAuthID, xAuthToken, contentType, addTimeGte, addTimeLte, callUuid, fromNumber, toNumber, recordingFormat);
        // TODO: test validations
    }

    /**
     * Delete a Recording
     *
     * Permanently delete a specific recording. Returns 204 No Content.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1AccountAuthIdRecordingDeleteTest() throws ApiException {
        String authId = null;
        String xAuthID = null;
        String xAuthToken = null;
        String contentType = null;
        api.apiV1AccountAuthIdRecordingDelete(authId, xAuthID, xAuthToken, contentType);
        // TODO: test validations
    }

    /**
     * Retrieve a Recording
     *
     * Get detailed information about a specific recording.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1AccountAuthIdRecordingGetTest() throws ApiException {
        String authId = null;
        String xAuthID = null;
        String xAuthToken = null;
        String contentType = null;
        api.apiV1AccountAuthIdRecordingGet(authId, xAuthID, xAuthToken, contentType);
        // TODO: test validations
    }

}
