/*
 * Vobiz API
 * Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.vobiz.api;

import ai.vobiz.ApiCallback;
import ai.vobiz.ApiClient;
import ai.vobiz.ApiException;
import ai.vobiz.ApiResponse;
import ai.vobiz.Configuration;
import ai.vobiz.Pair;
import ai.vobiz.ProgressRequestBody;
import ai.vobiz.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;



import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ApplicationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ApplicationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ApplicationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for apiV1AccountAuthIdApplicationDelete
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdApplicationDeleteCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/Account/{auth_id}/Application/{}/"
            .replace("{" + "auth_id" + "}", localVarApiClient.escapeString(authId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAuthID != null) {
            localVarHeaderParams.put("X-Auth-ID", localVarApiClient.parameterToString(xAuthID));
        }


        if (xAuthToken != null) {
            localVarHeaderParams.put("X-Auth-Token", localVarApiClient.parameterToString(xAuthToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "ApiKeyAuthID", "ApiKeyAuthToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call apiV1AccountAuthIdApplicationDeleteValidateBeforeCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authId' is set
        if (authId == null) {
            throw new ApiException("Missing the required parameter 'authId' when calling apiV1AccountAuthIdApplicationDelete(Async)");
        }

        return apiV1AccountAuthIdApplicationDeleteCall(authId, xAuthID, xAuthToken, contentType, _callback);

    }

    /**
     * Delete an Application
     * Delete an application. Returns 204 No Content.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void apiV1AccountAuthIdApplicationDelete(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType) throws ApiException {
        apiV1AccountAuthIdApplicationDeleteWithHttpInfo(authId, xAuthID, xAuthToken, contentType);
    }

    /**
     * Delete an Application
     * Delete an application. Returns 204 No Content.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> apiV1AccountAuthIdApplicationDeleteWithHttpInfo(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType) throws ApiException {
        okhttp3.Call localVarCall = apiV1AccountAuthIdApplicationDeleteValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete an Application (asynchronously)
     * Delete an application. Returns 204 No Content.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdApplicationDeleteAsync(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = apiV1AccountAuthIdApplicationDeleteValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for apiV1AccountAuthIdApplicationGet
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param limit Results per page (optional)
     * @param offset Pagination offset (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdApplicationGetCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/Account/{auth_id}/Application/"
            .replace("{" + "auth_id" + "}", localVarApiClient.escapeString(authId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAuthID != null) {
            localVarHeaderParams.put("X-Auth-ID", localVarApiClient.parameterToString(xAuthID));
        }


        if (xAuthToken != null) {
            localVarHeaderParams.put("X-Auth-Token", localVarApiClient.parameterToString(xAuthToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "ApiKeyAuthID", "ApiKeyAuthToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call apiV1AccountAuthIdApplicationGetValidateBeforeCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authId' is set
        if (authId == null) {
            throw new ApiException("Missing the required parameter 'authId' when calling apiV1AccountAuthIdApplicationGet(Async)");
        }

        return apiV1AccountAuthIdApplicationGetCall(authId, xAuthID, xAuthToken, contentType, limit, offset, _callback);

    }

    /**
     * List All Applications
     * Retrieve all applications with pagination.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param limit Results per page (optional)
     * @param offset Pagination offset (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void apiV1AccountAuthIdApplicationGet(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset) throws ApiException {
        apiV1AccountAuthIdApplicationGetWithHttpInfo(authId, xAuthID, xAuthToken, contentType, limit, offset);
    }

    /**
     * List All Applications
     * Retrieve all applications with pagination.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param limit Results per page (optional)
     * @param offset Pagination offset (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> apiV1AccountAuthIdApplicationGetWithHttpInfo(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset) throws ApiException {
        okhttp3.Call localVarCall = apiV1AccountAuthIdApplicationGetValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, limit, offset, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * List All Applications (asynchronously)
     * Retrieve all applications with pagination.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param limit Results per page (optional)
     * @param offset Pagination offset (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdApplicationGetAsync(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = apiV1AccountAuthIdApplicationGetValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, limit, offset, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for apiV1AccountAuthIdApplicationGet_0
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdApplicationGet_0Call(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/Account/{auth_id}/Application/{}/"
            .replace("{" + "auth_id" + "}", localVarApiClient.escapeString(authId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAuthID != null) {
            localVarHeaderParams.put("X-Auth-ID", localVarApiClient.parameterToString(xAuthID));
        }


        if (xAuthToken != null) {
            localVarHeaderParams.put("X-Auth-Token", localVarApiClient.parameterToString(xAuthToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "ApiKeyAuthID", "ApiKeyAuthToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call apiV1AccountAuthIdApplicationGet_0ValidateBeforeCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authId' is set
        if (authId == null) {
            throw new ApiException("Missing the required parameter 'authId' when calling apiV1AccountAuthIdApplicationGet_0(Async)");
        }

        return apiV1AccountAuthIdApplicationGet_0Call(authId, xAuthID, xAuthToken, contentType, _callback);

    }

    /**
     * Retrieve an Application
     * Get details of a specific application by its ID.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void apiV1AccountAuthIdApplicationGet_0(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType) throws ApiException {
        apiV1AccountAuthIdApplicationGet_0WithHttpInfo(authId, xAuthID, xAuthToken, contentType);
    }

    /**
     * Retrieve an Application
     * Get details of a specific application by its ID.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> apiV1AccountAuthIdApplicationGet_0WithHttpInfo(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType) throws ApiException {
        okhttp3.Call localVarCall = apiV1AccountAuthIdApplicationGet_0ValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Retrieve an Application (asynchronously)
     * Get details of a specific application by its ID.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdApplicationGet_0Async(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = apiV1AccountAuthIdApplicationGet_0ValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for apiV1AccountAuthIdApplicationPost
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdApplicationPostCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/api/v1/Account/{auth_id}/Application/"
            .replace("{" + "auth_id" + "}", localVarApiClient.escapeString(authId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAuthID != null) {
            localVarHeaderParams.put("X-Auth-ID", localVarApiClient.parameterToString(xAuthID));
        }


        if (xAuthToken != null) {
            localVarHeaderParams.put("X-Auth-Token", localVarApiClient.parameterToString(xAuthToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "ApiKeyAuthID", "ApiKeyAuthToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call apiV1AccountAuthIdApplicationPostValidateBeforeCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authId' is set
        if (authId == null) {
            throw new ApiException("Missing the required parameter 'authId' when calling apiV1AccountAuthIdApplicationPost(Async)");
        }

        return apiV1AccountAuthIdApplicationPostCall(authId, xAuthID, xAuthToken, contentType, body, _callback);

    }

    /**
     * Create Application
     * Create a new application with call handling URLs.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void apiV1AccountAuthIdApplicationPost(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body) throws ApiException {
        apiV1AccountAuthIdApplicationPostWithHttpInfo(authId, xAuthID, xAuthToken, contentType, body);
    }

    /**
     * Create Application
     * Create a new application with call handling URLs.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> apiV1AccountAuthIdApplicationPostWithHttpInfo(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body) throws ApiException {
        okhttp3.Call localVarCall = apiV1AccountAuthIdApplicationPostValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, body, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Create Application (asynchronously)
     * Create a new application with call handling URLs.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdApplicationPostAsync(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = apiV1AccountAuthIdApplicationPostValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, body, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for apiV1AccountAuthIdApplicationPost_0
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdApplicationPost_0Call(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/api/v1/Account/{auth_id}/Application/{}/"
            .replace("{" + "auth_id" + "}", localVarApiClient.escapeString(authId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAuthID != null) {
            localVarHeaderParams.put("X-Auth-ID", localVarApiClient.parameterToString(xAuthID));
        }


        if (xAuthToken != null) {
            localVarHeaderParams.put("X-Auth-Token", localVarApiClient.parameterToString(xAuthToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "ApiKeyAuthID", "ApiKeyAuthToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call apiV1AccountAuthIdApplicationPost_0ValidateBeforeCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authId' is set
        if (authId == null) {
            throw new ApiException("Missing the required parameter 'authId' when calling apiV1AccountAuthIdApplicationPost_0(Async)");
        }

        return apiV1AccountAuthIdApplicationPost_0Call(authId, xAuthID, xAuthToken, contentType, body, _callback);

    }

    /**
     * Update an Application
     * Update an existing application&#39;s settings.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void apiV1AccountAuthIdApplicationPost_0(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body) throws ApiException {
        apiV1AccountAuthIdApplicationPost_0WithHttpInfo(authId, xAuthID, xAuthToken, contentType, body);
    }

    /**
     * Update an Application
     * Update an existing application&#39;s settings.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> apiV1AccountAuthIdApplicationPost_0WithHttpInfo(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body) throws ApiException {
        okhttp3.Call localVarCall = apiV1AccountAuthIdApplicationPost_0ValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, body, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Update an Application (asynchronously)
     * Update an existing application&#39;s settings.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdApplicationPost_0Async(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = apiV1AccountAuthIdApplicationPost_0ValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, body, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for apiV1AccountAuthIdNumbersApplicationDelete
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdNumbersApplicationDeleteCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/account/{auth_id}/numbers/{}/application"
            .replace("{" + "auth_id" + "}", localVarApiClient.escapeString(authId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAuthID != null) {
            localVarHeaderParams.put("X-Auth-ID", localVarApiClient.parameterToString(xAuthID));
        }


        if (xAuthToken != null) {
            localVarHeaderParams.put("X-Auth-Token", localVarApiClient.parameterToString(xAuthToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "ApiKeyAuthID", "ApiKeyAuthToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call apiV1AccountAuthIdNumbersApplicationDeleteValidateBeforeCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authId' is set
        if (authId == null) {
            throw new ApiException("Missing the required parameter 'authId' when calling apiV1AccountAuthIdNumbersApplicationDelete(Async)");
        }

        return apiV1AccountAuthIdNumbersApplicationDeleteCall(authId, xAuthID, xAuthToken, contentType, _callback);

    }

    /**
     * Unlink Number from Application
     * Remove association between a phone number and application.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void apiV1AccountAuthIdNumbersApplicationDelete(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType) throws ApiException {
        apiV1AccountAuthIdNumbersApplicationDeleteWithHttpInfo(authId, xAuthID, xAuthToken, contentType);
    }

    /**
     * Unlink Number from Application
     * Remove association between a phone number and application.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> apiV1AccountAuthIdNumbersApplicationDeleteWithHttpInfo(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType) throws ApiException {
        okhttp3.Call localVarCall = apiV1AccountAuthIdNumbersApplicationDeleteValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Unlink Number from Application (asynchronously)
     * Remove association between a phone number and application.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdNumbersApplicationDeleteAsync(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = apiV1AccountAuthIdNumbersApplicationDeleteValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for apiV1AccountAuthIdNumbersApplicationPost
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdNumbersApplicationPostCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/api/v1/account/{auth_id}/numbers/{}/application"
            .replace("{" + "auth_id" + "}", localVarApiClient.escapeString(authId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAuthID != null) {
            localVarHeaderParams.put("X-Auth-ID", localVarApiClient.parameterToString(xAuthID));
        }


        if (xAuthToken != null) {
            localVarHeaderParams.put("X-Auth-Token", localVarApiClient.parameterToString(xAuthToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "ApiKeyAuthID", "ApiKeyAuthToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call apiV1AccountAuthIdNumbersApplicationPostValidateBeforeCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authId' is set
        if (authId == null) {
            throw new ApiException("Missing the required parameter 'authId' when calling apiV1AccountAuthIdNumbersApplicationPost(Async)");
        }

        return apiV1AccountAuthIdNumbersApplicationPostCall(authId, xAuthID, xAuthToken, contentType, body, _callback);

    }

    /**
     * Link Number to Application
     * Associate a phone number with an application.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void apiV1AccountAuthIdNumbersApplicationPost(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body) throws ApiException {
        apiV1AccountAuthIdNumbersApplicationPostWithHttpInfo(authId, xAuthID, xAuthToken, contentType, body);
    }

    /**
     * Link Number to Application
     * Associate a phone number with an application.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> apiV1AccountAuthIdNumbersApplicationPostWithHttpInfo(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body) throws ApiException {
        okhttp3.Call localVarCall = apiV1AccountAuthIdNumbersApplicationPostValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, body, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Link Number to Application (asynchronously)
     * Associate a phone number with an application.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdNumbersApplicationPostAsync(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = apiV1AccountAuthIdNumbersApplicationPostValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, body, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
