/*
 * Vobiz API
 * Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.vobiz.api;

import ai.vobiz.ApiCallback;
import ai.vobiz.ApiClient;
import ai.vobiz.ApiException;
import ai.vobiz.ApiResponse;
import ai.vobiz.Configuration;
import ai.vobiz.Pair;
import ai.vobiz.ProgressRequestBody;
import ai.vobiz.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;



import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PhoneNumbersApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PhoneNumbersApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PhoneNumbersApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for apiV1AccountAuthIdInventoryNumbersGet
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param country Filter by country code (optional)
     * @param page Page number (optional)
     * @param perPage Results per page (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdInventoryNumbersGetCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable String country, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/account/{auth_id}/inventory/numbers"
            .replace("{" + "auth_id" + "}", localVarApiClient.escapeString(authId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (perPage != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("per_page", perPage));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAuthID != null) {
            localVarHeaderParams.put("X-Auth-ID", localVarApiClient.parameterToString(xAuthID));
        }


        if (xAuthToken != null) {
            localVarHeaderParams.put("X-Auth-Token", localVarApiClient.parameterToString(xAuthToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "ApiKeyAuthID", "ApiKeyAuthToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call apiV1AccountAuthIdInventoryNumbersGetValidateBeforeCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable String country, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authId' is set
        if (authId == null) {
            throw new ApiException("Missing the required parameter 'authId' when calling apiV1AccountAuthIdInventoryNumbersGet(Async)");
        }

        return apiV1AccountAuthIdInventoryNumbersGetCall(authId, xAuthID, xAuthToken, contentType, country, page, perPage, _callback);

    }

    /**
     * List Inventory Numbers
     * Browse available phone numbers in inventory for purchase.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param country Filter by country code (optional)
     * @param page Page number (optional)
     * @param perPage Results per page (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void apiV1AccountAuthIdInventoryNumbersGet(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable String country, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage) throws ApiException {
        apiV1AccountAuthIdInventoryNumbersGetWithHttpInfo(authId, xAuthID, xAuthToken, contentType, country, page, perPage);
    }

    /**
     * List Inventory Numbers
     * Browse available phone numbers in inventory for purchase.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param country Filter by country code (optional)
     * @param page Page number (optional)
     * @param perPage Results per page (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> apiV1AccountAuthIdInventoryNumbersGetWithHttpInfo(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable String country, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage) throws ApiException {
        okhttp3.Call localVarCall = apiV1AccountAuthIdInventoryNumbersGetValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, country, page, perPage, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * List Inventory Numbers (asynchronously)
     * Browse available phone numbers in inventory for purchase.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param country Filter by country code (optional)
     * @param page Page number (optional)
     * @param perPage Results per page (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdInventoryNumbersGetAsync(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable String country, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = apiV1AccountAuthIdInventoryNumbersGetValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, country, page, perPage, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for apiV1AccountAuthIdNumbersE164NumberDelete
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdNumbersE164NumberDeleteCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/account/{auth_id}/numbers/:e164_number"
            .replace("{" + "auth_id" + "}", localVarApiClient.escapeString(authId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAuthID != null) {
            localVarHeaderParams.put("X-Auth-ID", localVarApiClient.parameterToString(xAuthID));
        }


        if (xAuthToken != null) {
            localVarHeaderParams.put("X-Auth-Token", localVarApiClient.parameterToString(xAuthToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "ApiKeyAuthID", "ApiKeyAuthToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call apiV1AccountAuthIdNumbersE164NumberDeleteValidateBeforeCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authId' is set
        if (authId == null) {
            throw new ApiException("Missing the required parameter 'authId' when calling apiV1AccountAuthIdNumbersE164NumberDelete(Async)");
        }

        return apiV1AccountAuthIdNumbersE164NumberDeleteCall(authId, xAuthID, xAuthToken, contentType, _callback);

    }

    /**
     * Unrent a Phone Number
     * Release (unrent) a phone number from your account.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void apiV1AccountAuthIdNumbersE164NumberDelete(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType) throws ApiException {
        apiV1AccountAuthIdNumbersE164NumberDeleteWithHttpInfo(authId, xAuthID, xAuthToken, contentType);
    }

    /**
     * Unrent a Phone Number
     * Release (unrent) a phone number from your account.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> apiV1AccountAuthIdNumbersE164NumberDeleteWithHttpInfo(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType) throws ApiException {
        okhttp3.Call localVarCall = apiV1AccountAuthIdNumbersE164NumberDeleteValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Unrent a Phone Number (asynchronously)
     * Release (unrent) a phone number from your account.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdNumbersE164NumberDeleteAsync(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = apiV1AccountAuthIdNumbersE164NumberDeleteValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for apiV1AccountAuthIdNumbersGet
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdNumbersGetCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/account/{auth_id}/numbers"
            .replace("{" + "auth_id" + "}", localVarApiClient.escapeString(authId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAuthID != null) {
            localVarHeaderParams.put("X-Auth-ID", localVarApiClient.parameterToString(xAuthID));
        }


        if (xAuthToken != null) {
            localVarHeaderParams.put("X-Auth-Token", localVarApiClient.parameterToString(xAuthToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "ApiKeyAuthID", "ApiKeyAuthToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call apiV1AccountAuthIdNumbersGetValidateBeforeCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authId' is set
        if (authId == null) {
            throw new ApiException("Missing the required parameter 'authId' when calling apiV1AccountAuthIdNumbersGet(Async)");
        }

        return apiV1AccountAuthIdNumbersGetCall(authId, xAuthID, xAuthToken, contentType, _callback);

    }

    /**
     * List Account Phone Numbers
     * Retrieve all phone numbers associated with your account.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void apiV1AccountAuthIdNumbersGet(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType) throws ApiException {
        apiV1AccountAuthIdNumbersGetWithHttpInfo(authId, xAuthID, xAuthToken, contentType);
    }

    /**
     * List Account Phone Numbers
     * Retrieve all phone numbers associated with your account.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> apiV1AccountAuthIdNumbersGetWithHttpInfo(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType) throws ApiException {
        okhttp3.Call localVarCall = apiV1AccountAuthIdNumbersGetValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * List Account Phone Numbers (asynchronously)
     * Retrieve all phone numbers associated with your account.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdNumbersGetAsync(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = apiV1AccountAuthIdNumbersGetValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for apiV1AccountAuthIdNumbersPurchaseFromInventoryPost
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdNumbersPurchaseFromInventoryPostCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/api/v1/account/{auth_id}/numbers/purchase-from-inventory"
            .replace("{" + "auth_id" + "}", localVarApiClient.escapeString(authId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xAuthID != null) {
            localVarHeaderParams.put("X-Auth-ID", localVarApiClient.parameterToString(xAuthID));
        }


        if (xAuthToken != null) {
            localVarHeaderParams.put("X-Auth-Token", localVarApiClient.parameterToString(xAuthToken));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        String[] localVarAuthNames = new String[] { "ApiKeyAuthID", "ApiKeyAuthToken" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call apiV1AccountAuthIdNumbersPurchaseFromInventoryPostValidateBeforeCall(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'authId' is set
        if (authId == null) {
            throw new ApiException("Missing the required parameter 'authId' when calling apiV1AccountAuthIdNumbersPurchaseFromInventoryPost(Async)");
        }

        return apiV1AccountAuthIdNumbersPurchaseFromInventoryPostCall(authId, xAuthID, xAuthToken, contentType, body, _callback);

    }

    /**
     * Purchase from Inventory
     * Purchase a phone number from available inventory.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void apiV1AccountAuthIdNumbersPurchaseFromInventoryPost(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body) throws ApiException {
        apiV1AccountAuthIdNumbersPurchaseFromInventoryPostWithHttpInfo(authId, xAuthID, xAuthToken, contentType, body);
    }

    /**
     * Purchase from Inventory
     * Purchase a phone number from available inventory.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> apiV1AccountAuthIdNumbersPurchaseFromInventoryPostWithHttpInfo(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body) throws ApiException {
        okhttp3.Call localVarCall = apiV1AccountAuthIdNumbersPurchaseFromInventoryPostValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, body, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Purchase from Inventory (asynchronously)
     * Purchase a phone number from available inventory.
     * @param authId  (required)
     * @param xAuthID  (optional)
     * @param xAuthToken  (optional)
     * @param contentType  (optional)
     * @param body  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call apiV1AccountAuthIdNumbersPurchaseFromInventoryPostAsync(@javax.annotation.Nonnull String authId, @javax.annotation.Nullable String xAuthID, @javax.annotation.Nullable String xAuthToken, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = apiV1AccountAuthIdNumbersPurchaseFromInventoryPostValidateBeforeCall(authId, xAuthID, xAuthToken, contentType, body, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
