/*
 * Vobiz API
 *
 * Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Vobiz.Api;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Vobiz.Test.Api
{
    /// <summary>
    ///  Class for testing CDRApi
    /// </summary>
    public sealed class CDRApiTests : ApiTestsBase
    {
        private readonly ICDRApi _instance;

        public CDRApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ICDRApi>();
        }

        /// <summary>
        /// Test ApiV1AccountAccountIdCdrGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ApiV1AccountAccountIdCdrGetAsyncTest()
        {
            string accountId = default!;
            Client.Option<string> xAuthID = default!;
            Client.Option<string> xAuthToken = default!;
            Client.Option<string> contentType = default!;
            Client.Option<string> startDate = default!;
            Client.Option<string> endDate = default!;
            Client.Option<int> perPage = default!;
            Client.Option<int> page = default!;
            await _instance.ApiV1AccountAccountIdCdrGetAsync(accountId, xAuthID, xAuthToken, contentType, startDate, endDate, perPage, page);
        }
    }
}
