/*
 * Vobiz API
 *
 * Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System.Collections.Generic;
using System.Security.Cryptography;
using Vobiz.Client;
using Vobiz.Api;
using Vobiz.Extensions;
using Xunit;

namespace Vobiz.Test.Api
{
    /// <summary>
    ///  Tests the dependency injection.
    /// </summary>
    public class DependencyInjectionTest
    {
        private readonly IHost _hostUsingConfigureWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((context, services, options) =>
            {
                ApiKeyToken apiKeyToken1 = new("<token>", ClientUtils.ApiKeyHeader.X_Auth_ID, timeout: TimeSpan.FromSeconds(1));
                options.AddTokens(apiKeyToken1);

                ApiKeyToken apiKeyToken2 = new("<token>", ClientUtils.ApiKeyHeader.X_Auth_Token, timeout: TimeSpan.FromSeconds(1));
                options.AddTokens(apiKeyToken2);
            })
            .Build();

        private readonly IHost _hostUsingConfigureWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((context, services, options) =>
            {
                ApiKeyToken apiKeyToken1 = new("<token>", ClientUtils.ApiKeyHeader.X_Auth_ID, timeout: TimeSpan.FromSeconds(1));
                options.AddTokens(apiKeyToken1);

                ApiKeyToken apiKeyToken2 = new("<token>", ClientUtils.ApiKeyHeader.X_Auth_Token, timeout: TimeSpan.FromSeconds(1));
                options.AddTokens(apiKeyToken2);
                options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
            })
            .Build();

        private readonly IHost _hostUsingAddWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {
                    ApiKeyToken apiKeyToken1 = new("<token>", ClientUtils.ApiKeyHeader.X_Auth_ID, timeout: TimeSpan.FromSeconds(1));
                    options.AddTokens(apiKeyToken1);

                    ApiKeyToken apiKeyToken2 = new("<token>", ClientUtils.ApiKeyHeader.X_Auth_Token, timeout: TimeSpan.FromSeconds(1));
                    options.AddTokens(apiKeyToken2);
                });
            })
            .Build();

        private readonly IHost _hostUsingAddWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {
                    ApiKeyToken apiKeyToken1 = new("<token>", ClientUtils.ApiKeyHeader.X_Auth_ID, timeout: TimeSpan.FromSeconds(1));
                    options.AddTokens(apiKeyToken1);

                    ApiKeyToken apiKeyToken2 = new("<token>", ClientUtils.ApiKeyHeader.X_Auth_Token, timeout: TimeSpan.FromSeconds(1));
                    options.AddTokens(apiKeyToken2);
                    options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
                });
            })
            .Build();

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithAClientTest()
        {
            var accountApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IAccountApi>();
            Assert.True(accountApi.HttpClient.BaseAddress != null);

            var applicationApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IApplicationApi>();
            Assert.True(applicationApi.HttpClient.BaseAddress != null);

            var cDRApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<ICDRApi>();
            Assert.True(cDRApi.HttpClient.BaseAddress != null);

            var callApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<ICallApi>();
            Assert.True(callApi.HttpClient.BaseAddress != null);

            var conferenceApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IConferenceApi>();
            Assert.True(conferenceApi.HttpClient.BaseAddress != null);

            var endpointApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IEndpointApi>();
            Assert.True(endpointApi.HttpClient.BaseAddress != null);

            var phoneNumbersApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IPhoneNumbersApi>();
            Assert.True(phoneNumbersApi.HttpClient.BaseAddress != null);

            var recordingApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IRecordingApi>();
            Assert.True(recordingApi.HttpClient.BaseAddress != null);

            var subAccountApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<ISubAccountApi>();
            Assert.True(subAccountApi.HttpClient.BaseAddress != null);

            var trunkApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<ITrunkApi>();
            Assert.True(trunkApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithoutAClientTest()
        {
            var accountApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IAccountApi>();
            Assert.True(accountApi.HttpClient.BaseAddress != null);

            var applicationApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IApplicationApi>();
            Assert.True(applicationApi.HttpClient.BaseAddress != null);

            var cDRApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<ICDRApi>();
            Assert.True(cDRApi.HttpClient.BaseAddress != null);

            var callApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<ICallApi>();
            Assert.True(callApi.HttpClient.BaseAddress != null);

            var conferenceApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IConferenceApi>();
            Assert.True(conferenceApi.HttpClient.BaseAddress != null);

            var endpointApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IEndpointApi>();
            Assert.True(endpointApi.HttpClient.BaseAddress != null);

            var phoneNumbersApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IPhoneNumbersApi>();
            Assert.True(phoneNumbersApi.HttpClient.BaseAddress != null);

            var recordingApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IRecordingApi>();
            Assert.True(recordingApi.HttpClient.BaseAddress != null);

            var subAccountApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<ISubAccountApi>();
            Assert.True(subAccountApi.HttpClient.BaseAddress != null);

            var trunkApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<ITrunkApi>();
            Assert.True(trunkApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithAClientTest()
        {
            var accountApi = _hostUsingAddWithAClient.Services.GetRequiredService<IAccountApi>();
            Assert.True(accountApi.HttpClient.BaseAddress != null);
            
            var applicationApi = _hostUsingAddWithAClient.Services.GetRequiredService<IApplicationApi>();
            Assert.True(applicationApi.HttpClient.BaseAddress != null);
            
            var cDRApi = _hostUsingAddWithAClient.Services.GetRequiredService<ICDRApi>();
            Assert.True(cDRApi.HttpClient.BaseAddress != null);
            
            var callApi = _hostUsingAddWithAClient.Services.GetRequiredService<ICallApi>();
            Assert.True(callApi.HttpClient.BaseAddress != null);
            
            var conferenceApi = _hostUsingAddWithAClient.Services.GetRequiredService<IConferenceApi>();
            Assert.True(conferenceApi.HttpClient.BaseAddress != null);
            
            var endpointApi = _hostUsingAddWithAClient.Services.GetRequiredService<IEndpointApi>();
            Assert.True(endpointApi.HttpClient.BaseAddress != null);
            
            var phoneNumbersApi = _hostUsingAddWithAClient.Services.GetRequiredService<IPhoneNumbersApi>();
            Assert.True(phoneNumbersApi.HttpClient.BaseAddress != null);
            
            var recordingApi = _hostUsingAddWithAClient.Services.GetRequiredService<IRecordingApi>();
            Assert.True(recordingApi.HttpClient.BaseAddress != null);
            
            var subAccountApi = _hostUsingAddWithAClient.Services.GetRequiredService<ISubAccountApi>();
            Assert.True(subAccountApi.HttpClient.BaseAddress != null);
            
            var trunkApi = _hostUsingAddWithAClient.Services.GetRequiredService<ITrunkApi>();
            Assert.True(trunkApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithoutAClientTest()
        {
            var accountApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IAccountApi>();
            Assert.True(accountApi.HttpClient.BaseAddress != null);

            var applicationApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IApplicationApi>();
            Assert.True(applicationApi.HttpClient.BaseAddress != null);

            var cDRApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<ICDRApi>();
            Assert.True(cDRApi.HttpClient.BaseAddress != null);

            var callApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<ICallApi>();
            Assert.True(callApi.HttpClient.BaseAddress != null);

            var conferenceApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IConferenceApi>();
            Assert.True(conferenceApi.HttpClient.BaseAddress != null);

            var endpointApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IEndpointApi>();
            Assert.True(endpointApi.HttpClient.BaseAddress != null);

            var phoneNumbersApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IPhoneNumbersApi>();
            Assert.True(phoneNumbersApi.HttpClient.BaseAddress != null);

            var recordingApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IRecordingApi>();
            Assert.True(recordingApi.HttpClient.BaseAddress != null);

            var subAccountApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<ISubAccountApi>();
            Assert.True(subAccountApi.HttpClient.BaseAddress != null);

            var trunkApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<ITrunkApi>();
            Assert.True(trunkApi.HttpClient.BaseAddress != null);
        }
    }
}
