/*
 * Vobiz API
 *
 * Complete Vobiz API collection covering all endpoints: Calls, Conferences, Recordings, Account, Phone Numbers, Applications, Endpoints, Trunks, Sub-Accounts, and CDR.  Base URL: https://api.vobiz.ai  Authentication: All requests require X-Auth-ID and X-Auth-Token headers.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Microsoft.Extensions.DependencyInjection;
using Vobiz.Api;
using Xunit;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Vobiz.Test.Api
{
    public sealed class SubAccountApiTests : ApiTestsBase
    {
        private readonly ISubAccountApi _instance;

        public SubAccountApiTests() : base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ISubAccountApi>();
        }

        [Fact]
        public void ServiceResolves()
        {
            Assert.NotNull(_instance);
        }

        [Theory]
        [InlineData(nameof(ISubAccountApi.ApiV1AccountsAccountIdSubAccountsGetAsync))]
        [InlineData(nameof(ISubAccountApi.ApiV1AccountsAccountIdSubAccountsPostAsync))]
        [InlineData(nameof(ISubAccountApi.ApiV1AccountsAccountIdSubAccountsSubAccountIdDeleteAsync))]
        [InlineData(nameof(ISubAccountApi.ApiV1AccountsAccountIdSubAccountsSubAccountIdGetAsync))]
        [InlineData(nameof(ISubAccountApi.ApiV1AccountsAccountIdSubAccountsSubAccountIdPutAsync))]
        public void OperationMethodExists(string methodName)
        {
            Assert.Contains(typeof(ISubAccountApi).GetMethods(), m => m.Name == methodName);
        }
    }
}
